import { Injectable, Logger } from "@nestjs/common";
import type { OnModuleDestroy } from "@nestjs/common";
import { Worker, type Job } from "bullmq";import IORedis from "ioredis";
import { PrivacyRepository, ProductionDatabase } from "@papadata/database";import { ObjectStorageClient } from "@papadata/storage";
export type PlatformJobPayload={readonly jobType:"report"|"privacy_request"|"reconciliation"|"retention"|"ai_evaluation";readonly tenantId:string;readonly workspaceId:string|null;readonly payload:Readonly<Record<string,unknown>>;readonly idempotencyKey:string};
@Injectable()
export class PlatformWorkerService implements OnModuleDestroy{private readonly logger=new Logger(PlatformWorkerService.name);private readonly connection=new IORedis(process.env.REDIS_URL??"redis://redis:6379",{maxRetriesPerRequest:null});private readonly database=new ProductionDatabase({connectionString:process.env.DATABASE_URL??"postgresql://papadata_app:papadata-local@postgres:5432/papadata",max:8,statementTimeoutMs:30000});private readonly storage=new ObjectStorageClient({driver:process.env.PAPADATA_STORAGE_DRIVER==="gcs"?"gcs":"minio",bucket:process.env.PAPADATA_STORAGE_BUCKET??"papadata-local",endpoint:process.env.PAPADATA_STORAGE_ENDPOINT??null,accessKey:process.env.PAPADATA_STORAGE_ACCESS_KEY??null,secretKey:process.env.PAPADATA_STORAGE_SECRET_KEY??null,projectId:process.env.GOOGLE_CLOUD_PROJECT??null});private readonly worker=new Worker<PlatformJobPayload>("papadata-platform-jobs",job=>this.process(job),{connection:this.connection,concurrency:Number(process.env.PLATFORM_WORKER_CONCURRENCY??4),lockDuration:60000,stalledInterval:30000});
 private async process(job:Job<PlatformJobPayload>):Promise<object>{this.logger.log(`Processing platform job ${job.data.jobType}`);switch(job.data.jobType){case"report":return this.processReport(job.data);case"privacy_request":return this.processPrivacy(job.data);case"reconciliation":return{status:"verification_pending",limitations:["Provider-specific reconciliation handler must be configured."]};case"retention":return{status:"verification_pending",limitations:["Backup cutoff evidence is external to the worker."]};case"ai_evaluation":return{status:"blocked",limitations:["Live provider evaluation requires an enabled provider route."]};}}
 private async processReport(data:PlatformJobPayload):Promise<object>{const reportId=String(data.payload.reportId??"");const rows=await this.database.query<Record<string,unknown>>(`select * from app.report_requests where id=$1 and tenant_id=$2 and workspace_id is not distinct from $3 limit 1`,[reportId,data.tenantId,data.workspaceId]);const report=rows[0];if(!report)throw new Error("Report request not found");await this.database.pool.query(`update app.report_requests set status='generating' where id=$1`,[reportId]);const content=Buffer.from(JSON.stringify({reportId,generatedAt:new Date().toISOString(),reportType:report.report_type,dateFrom:report.date_from,dateTo:report.date_to,filters:report.filters,rows:[]},null,2));const objectKey=`reports/${data.tenantId}/${data.workspaceId??"tenant"}/${reportId}.json`;const stored=await this.storage.put(objectKey,content,"application/json");await this.database.pool.query(`update app.report_requests set status='ready',object_key=$2,checksum_sha256=$3,size_bytes=$4,content_type='application/json',ready_at=now(),expires_at=now()+interval '7 days' where id=$1`,[reportId,stored.key,stored.checksumSha256,stored.sizeBytes]);return{reportId,status:"ready",objectKey};}
 private async processPrivacy(data:PlatformJobPayload):Promise<object>{const requestId=String(data.payload.requestId??"");const repository=new PrivacyRepository(this.database);for(const system of["database","cache","search_index","queue","object_storage","provider","ai","backup"])await repository.updateTarget({requestId,system,status:"verification_pending",evidenceReference:null,errorCode:null});await this.database.pool.query(`update app.privacy_requests set status='verification_pending' where id=$1`,[requestId]);return{requestId,status:"verification_pending",verified:false};}
 async onModuleDestroy():Promise<void>{await this.worker.close();await this.connection.quit();await this.database.close();}}
