import { useRef, useState } from 'react';
import type { BillingOverview, BillingOffer, BillingSessionCommand, BillingInvoiceView } from '@papadata/contracts';
import { Button, ProductSectionFrame } from '../../design-system';
import type { RemoteState } from '../../runtime/shared/data/useRemoteResource';
import { safeRandomUUID } from '../../runtime/shared/id/safeRandomUUID';
import { useProductQuery } from '../../runtime/app/routing/productRoutes';
import { ProductDataState, ProductViewNav } from '../shared/ProductDataState';
import { useProductLocale } from '../shared/useProductLocale';
import { OperationsFrame, OperationsDialog, OperationError } from './OperationsFrame';
export type BillingOperationsScreenProps={data:BillingOverview|null;state:RemoteState;problem?:string|null;onReload?:()=>void;onSession?:(input:BillingSessionCommand)=>Promise<void>;onNextInvoices?:()=>void;onFirstInvoices?:()=>void;demo?:boolean};
const views=['subscription','plans','usage','invoices','payment'] as const;
type View=typeof views[number];
function money(amount:number,currency:string,language:string){return ['PLN','EUR','USD'].includes(currency)?new Intl.NumberFormat(language,{style:'currency',currency}).format(amount/100):`${amount} minor units (${currency})`;}
export function BillingOperationsScreen({data,state,problem,onReload,onSession,onNextInvoices,onFirstInvoices,demo}:BillingOperationsScreenProps){
 const {t,language}=useProductLocale(),{params,location,update}=useProductQuery(),requested=params.get('billingView')??({plany:'plans',faktury:'invoices','uzycie-i-limity':'usage',platnosci:'payment','metody-platnosci':'payment'} as Record<string,string>)[location.split('?')[0]!.split('/').pop()??''];
 const view:View=(views as readonly string[]).includes(requested??'')?requested as View:'subscription';
 const cycle=params.get('billingCycle')==='annual'?'annual':'monthly';
 const [action,setAction]=useState<{kind:'checkout'|'portal';offer?:BillingOffer;resumeId?:string}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[invoice,setInvoice]=useState<BillingInvoiceView|null>(null),request=useRef<{body:string;id:string}|null>(null);
 const labels:Record<View,[string,string]>={subscription:['Subskrypcja','Subscription'],plans:['Plany','Plans'],usage:['Uzycie i limity','Usage and limits'],invoices:['Faktury','Invoices'],payment:['Metody platnosci','Payment methods']};
 async function confirm(){if(!action||!onSession||busy)return;const body=JSON.stringify(action);if(request.current?.body!==body)request.current={body,id:safeRandomUUID()};setError(null);setBusy(true);try{await onSession({requestId:action.resumeId??request.current.id,action:action.kind,...(action.offer?{offerId:action.offer.priceId}:{})});setAction(null);}catch(cause){setError(cause instanceof Error?cause.message:'Provider session failed');}finally{setBusy(false);}}
 const manage=()=>{setAction({kind:'portal'});setError(null);};
 return <OperationsFrame title={t('Subskrypcja i płatności','Subscription and payments')} description={t('Twój plan, wykorzystanie i dokumenty rozliczeniowe.','Your plan, usage and billing documents.')} onReload={onReload} demo={demo}>
 <ProductViewNav label={t('Obszary rozliczen','Billing sections')} active={view} items={views.map(id=>({id,label:t(...labels[id])}))} onChange={id=>update({billingView:id})}/>
 <ProductDataState state={state} problem={problem} onRetry={onReload}>{data&&<>
 <p className="pd-operations__notice" role="status">{data.mode==='live'?t('TRYB RZECZYWISTY: zatwierdzenie u dostawcy moze spowodowac obciazenie.','LIVE MODE: confirmation at the provider may create a real charge.'):data.mode==='test'?t('TRYB TESTOWY: uzywaj tylko danych testowych dostawcy.','TEST MODE: use only provider test payment data.'):t('Platnosci nie sa skonfigurowane. Nie pokazujemy wymyslonych cen ani metod.','Payments are not configured. No fabricated prices or methods are shown.')}</p>
 {params.get('providerReturn')==='1'&&<p role="status">{t('Powrot od dostawcy nie jest potwierdzeniem platnosci. Sprawdz stan subskrypcji i czas potwierdzenia serwera; odswiez, jezeli webhook jest jeszcze przetwarzany.','Returning from the provider is not payment confirmation. Check subscription status and server confirmation time; refresh if the webhook is still processing.')}</p>}
 {data.pendingCheckout&&onSession&&data.canManage&&<div className="pd-operations__notice"><p>{t('Otwarta proba platnosci wygasa','Pending checkout expires')}: {data.pendingCheckout.expiresAt}</p><Button variant="secondary" onClick={()=>{const offer=data.offers.find(item=>item.priceId===data.pendingCheckout?.offerId);if(offer){setAction({kind:'checkout',offer,resumeId:data.pendingCheckout!.requestId});setError(null);}}} disabled={!data.offers.some(item=>item.priceId===data.pendingCheckout?.offerId)}>{t('Wznow te sama platnosc','Resume the same checkout')}</Button></div>}
 {view==='subscription'&&<ProductSectionFrame icon="billing" title={t('Biezaca subskrypcja','Current subscription')}>
 <dl className="pd-operations__facts"><div><dt>{t('Plan workspace','Workspace plan')}</dt><dd>{data.subscription.plan}</dd></div><div><dt>{t('Stan w PapaData','PapaData status')}</dt><dd>{data.subscription.status}</dd></div><div><dt>{t('Stan dostawcy','Provider status')}</dt><dd>{data.subscription.providerStatus??t('Brak potwierdzenia','Not confirmed')}</dd></div><div><dt>{t('Koniec okresu','Period end')}</dt><dd>{data.subscription.currentPeriodEnd??'--'}</dd></div><div><dt>{t('Odczyt potwierdzony przez worker','Worker confirmation')}</dt><dd>{data.subscription.providerCheckedAt??'--'}</dd></div><div><dt>{t('Anulowanie z koncem okresu','Cancel at period end')}</dt><dd>{data.subscription.cancelAtPeriodEnd===null?'--':data.subscription.cancelAtPeriodEnd?t('Tak','Yes'):t('Nie','No')}</dd></div></dl>
 {data.subscription.status==='past_due'&&<p role="alert">{t('Platnosc wymaga uwagi. Otworz portal, sprawdz zaleglosc i metode platnosci. Dostep nie zostaje przywrocony samym powrotem do tej strony.','Payment needs attention. Open the portal and review the balance and payment method. Returning to this page does not restore access by itself.')}</p>}
 <div className="pd-operations__actions"><Button onClick={()=>update({billingView:'plans'})}>{t('Porownaj plany','Compare plans')}</Button>{data.portalEnabled&&onSession&&data.canManage&&<Button variant="secondary" onClick={manage}>{t('Zmien, odnow lub anuluj u dostawcy','Change, renew or cancel with provider')}</Button>}</div>
 <p>{t('Termin zmiany, prorata, podatki i skutki anulowania sa przedstawiane w portalu przed zatwierdzeniem. Nie sa szacowane przez ten ekran.','Effective date, proration, tax and cancellation effects are shown in the provider portal before confirmation. This screen does not estimate them.')}</p>
 </ProductSectionFrame>}
 {view==='plans'&&<ProductSectionFrame icon="billing" title={t('Dostepne oferty','Available offers')}>
 <ProductViewNav label={t('Okres rozliczeniowy','Billing interval')} active={cycle} items={[{id:'monthly',label:t('Miesiecznie','Monthly')},{id:'annual',label:t('Rocznie','Annual')}]} onChange={id=>update({billingCycle:id})}/>
 {data.offers.filter(offer=>offer.cycle===cycle).length===0?<p>{t('Brak zweryfikowanych ofert dla tego okresu.','No verified offers for this interval.')}</p>:<div className="pd-operations__offers">{data.offers.filter(offer=>offer.cycle===cycle).map(offer=><section key={offer.priceId} className="pd-operations__offer"><h3>{offer.name}</h3><p><strong>{money(offer.unitAmount,offer.currency,language)}</strong> / {offer.cycle==='annual'?t('rok','year'):t('miesiac','month')}</p><p>{t('Sposob rozliczenia podatku','Tax behavior')}: {offer.taxBehavior}</p><Button disabled={!onSession||!data.canManage||data.mode==='disabled'} onClick={()=>{setError(null);setAction(data.subscription.subscriptionConfigured?{kind:'portal'}:{kind:'checkout',offer});}}>{data.subscription.subscriptionConfigured?t('Zmien plan w portalu','Change plan in portal'):t('Wybierz i przejdz do platnosci','Choose and proceed to payment')}</Button></section>)}</div>}
 <p>{t('Kwota roczna jest kwota za caly rok. Metody platnosci, podatek i ostateczne podsumowanie przedstawia dostawca.','The annual amount is for the full year. Payment methods, tax and final totals are presented by the provider.')}</p></ProductSectionFrame>}
 {view==='usage'&&<ProductSectionFrame icon="data" title={t('Uzycie planu','Plan usage')}><dl className="pd-operations__facts"><div><dt>{t('Polaczone zrodla','Connected sources')}</dt><dd>{data.usage.connectedSources} / {data.usage.maxSources}</dd></div></dl><p>{t('Limit dotyczy katalogu zrodel w aktualnym planie. Nie przedstawia zuzycia tokenow AI, miejsca dyskowego ani pozycji faktury.','This is the source limit of the current plan, not AI token, storage or invoice usage.')}</p>{data.usage.connectedSources>data.usage.maxSources&&<p role="alert">{t('Liczba zrodel przekracza limit aktualnego planu. Zweryfikuj konfiguracje przed dodaniem kolejnego polaczenia.','Source count exceeds the current plan limit. Review configuration before adding a connection.')}</p>}</ProductSectionFrame>}
 {view==='payment'&&<ProductSectionFrame icon="billing" title={t('Bezpieczna obsluga platnosci','Secure payment management')}><p>{t('Dane kart nie trafiaja do formularza PapaData. Dodanie lub zmiana metody oraz ponowienie platnosci odbywa sie w portalu dostawcy. Dostepnosc metod zalezy od jego konfiguracji.','Card details do not enter a PapaData form. Add or change a payment method and retry a payment in the provider portal. Available methods depend on its configuration.')}</p><Button disabled={!data.portalEnabled||!data.canManage||!onSession} onClick={manage}>{t('Otworz metody i platnosci','Open payment methods and payments')}</Button>{!data.portalEnabled&&<p>{t('Portal wymaga przypisanego klienta i konfiguracji po stronie operatora.','The portal requires a linked customer and operator configuration.')}</p>}</ProductSectionFrame>}
 {view==='invoices'&&<ProductSectionFrame icon="billing" title={t('Faktury od dostawcy','Provider invoices')}>
 {!data.subscription.customerConfigured?<p>{t('Klient rozliczeniowy nie zostal jeszcze przypisany.','A billing customer has not been linked yet.')}</p>:data.invoices.length===0?<p>{t('Brak dokumentow w tej odpowiedzi. Sprawdz ponizsze ograniczenia odczytu.','No documents in this response. Check read limitations below.')}</p>:<div className="pd-operations__table" tabIndex={0}><table><thead><tr><th>{t('Numer','Number')}</th><th>{t('Data','Date')}</th><th>{t('Kwota','Total')}</th><th>{t('Do zaplaty','Remaining')}</th><th>{t('Stan','Status')}</th><th>{t('Dokument','Document')}</th></tr></thead><tbody>{data.invoices.map(row=><tr key={row.id}><td><Button variant="ghost" size="small" onClick={()=>setInvoice(row)}>{row.number??row.id}</Button></td><td>{row.createdAt}</td><td>{money(row.total,row.currency,language)}</td><td>{money(row.due,row.currency,language)}</td><td>{row.status}</td><td>{row.pdfUrl?<a href={row.pdfUrl} target="_blank" rel="noopener noreferrer">PDF</a>:t('PDF niedostepny','PDF unavailable')}</td></tr>)}</tbody></table></div>}
 <p>{t('KSeF: brak podlaczonego adaptera. Faktura Stripe nie jest potwierdzeniem przyjecia przez KSeF. Korekty wymagaja procesu u wystawcy.','KSeF: no adapter connected. A Stripe invoice is not KSeF acceptance evidence. Corrections require the issuer\'s process.')}</p><div className="pd-operations__actions">{onFirstInvoices&&<Button variant="ghost" onClick={onFirstInvoices}>{t('Najnowsze','Latest')}</Button>}{onNextInvoices&&data.invoicesHasMore&&<Button variant="secondary" onClick={onNextInvoices}>{t('Starsze faktury','Older invoices')}</Button>}</div>
 </ProductSectionFrame>}
 <details><summary>{t('Zrodlo i ograniczenia','Source and limitations')}</summary>{data.limitations.map(message=><p key={message}>{message}</p>)}</details>
 {!data.canManage&&<p>{t('Tryb odczytu. Zarzadzanie rozliczeniami wymaga billing.manage.','Read-only. Billing management requires billing.manage.')}</p>}
 </>}</ProductDataState>
 <OperationsDialog open={action!==null} title={t('Przejsc do dostawcy rozliczen?','Continue to the billing provider?')} busy={busy} onClose={()=>setAction(null)}>
 <p>{action?.offer?`${action.offer.name}: ${money(action.offer.unitAmount,action.offer.currency,language)} / ${action.offer.cycle}`:t('Zmiany subskrypcji, metody platnosci i anulowanie zatwierdzisz na stronie dostawcy.','Subscription changes, payment methods and cancellation will be confirmed at the provider.')}</p><p>{data?.mode==='live'?t('To rzeczywiste rozliczenie, nie symulacja.','This is live billing, not a simulation.'):t('Tryb testowy lub demonstracyjny.','Test or demonstration mode.')}</p><OperationError message={error}/><Button disabled={busy} onClick={()=>void confirm()}>{t('Przejdz dalej','Continue')}</Button></OperationsDialog>
 <OperationsDialog open={invoice!==null} title={t('Szczegoly faktury','Invoice details')} onClose={()=>setInvoice(null)}>{invoice&&<><dl><dt>{t('Identyfikator dostawcy','Provider id')}</dt><dd>{invoice.id}</dd><dt>{t('Numer','Number')}</dt><dd>{invoice.number??'--'}</dd><dt>{t('Termin platnosci','Due date')}</dt><dd>{invoice.dueAt??'--'}</dd><dt>{t('Status','Status')}</dt><dd>{invoice.status}</dd></dl>{invoice.paymentUrl&&<a href={invoice.paymentUrl} target="_blank" rel="noopener noreferrer">{t('Otworz dokument u wystawcy','Open with the issuer')}</a>}</>}</OperationsDialog>
 </OperationsFrame>;
}
