import { useRef, useState, type ReactNode } from 'react';
import { migratedSourcePriorityPolicy, type QualityOverview, type QualityDataset, type QualityReviewCommand, type QualityReview } from '@papadata/contracts';
import { Button, ExplorerTable, ProductSectionFrame } from '../../design-system';
import type { ExplorerTableColumn } from '../../design-system/components/Domain/ExplorerTable/ExplorerTable';
import type { RemoteState } from '../../runtime/shared/data/useRemoteResource';
import { useProductQuery } from '../../runtime/app/routing/productRoutes';
import { safeRandomUUID } from '../../runtime/shared/id/safeRandomUUID';
import { ProductDataState, ProductViewNav } from '../shared/ProductDataState';
import { useProductLocale } from '../shared/useProductLocale';
import { OperationsFrame, OperationsDialog, OperationError } from './OperationsFrame';
export type DataQualityScreenProps={data:QualityOverview|null;state:RemoteState;problem?:string|null;onReload?:()=>void;onReview?:(input:QualityReviewCommand)=>Promise<QualityReview>;onSource?:(id:string)=>void;renderLineage?:(dataset:QualityDataset)=>ReactNode;demo?:boolean};
type DatasetRow=QualityDataset & {id:string};
const views=['datasets','lineage','reconciliation','sources'] as const;
export function DataQualityScreen({data,state,problem,onReload,onReview,onSource,renderLineage,demo}:DataQualityScreenProps){
 const {t}=useProductLocale(),{params,update}=useProductQuery(),requested=params.get('qualityView'),view=(views as readonly string[]).includes(requested??'')?requested as typeof views[number]:'datasets';
 const [review,setReview]=useState<DatasetRow|null>(null),[note,setNote]=useState(''),[disposition,setDisposition]=useState<QualityReview['disposition']>('investigating'),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),request=useRef<{body:string;id:string}|null>(null);
 const rows:readonly DatasetRow[]=data?.datasets.map(row=>({...row,id:`${row.connectionId}:${row.stream}`}))??[];
 const selected=rows.find(row=>row.connectionId===params.get('qualitySource')&&row.stream===params.get('qualityStream'))??null;
 const labels:Record<typeof views[number],[string,string]>={datasets:['Zbiory danych','Datasets'],lineage:['Pochodzenie','Lineage'],reconciliation:['Rekoncyliacja importu','Import reconciliation'],sources:['Nakladanie i reguly','Overlap and rules']};
 const columns:readonly ExplorerTableColumn<DatasetRow>[]=[
  {id:'provider',label:t('Dostawca','Provider'),render:r=>r.provider,sortAccessor:r=>r.provider},
  {id:'stream',label:t('Strumien','Stream'),render:r=><Button variant="ghost" size="small" onClick={()=>update({qualityView:'lineage',qualitySource:r.connectionId,qualityStream:r.stream})}>{r.stream}</Button>,sortAccessor:r=>r.stream},
  {id:'source',label:t('Rekordy zrodlowe','Source records'),render:r=>r.sourceRecords,sortAccessor:r=>r.sourceRecords,align:'right'},
  {id:'canonical',label:t('Rekordy kanoniczne','Canonical records'),render:r=>r.canonicalRecords,sortAccessor:r=>r.canonicalRecords,align:'right'},
  {id:'failed',label:t('Bledne/czesciowe partie','Failed/partial batches'),render:r=>r.failedBatches,sortAccessor:r=>r.failedBatches,align:'right'},
  {id:'updated',label:t('Ostatni import','Last ingestion'),render:r=>r.lastIngestedAt??'--',sortAccessor:r=>r.lastIngestedAt},
  {id:'review',label:t('Przeglad','Review'),render:r=>{const saved=data?.reviews.find(item=>item.connectionId===r.connectionId&&item.stream===r.stream);return <><span>{saved?.disposition??t('Nie oceniono','Not reviewed')}</span>{onReview&&<Button size="small" variant="ghost" onClick={()=>{setReview(r);setDisposition(saved?.disposition??'investigating');setNote(saved?.note??'');setError(null);}}>{t('Zapisz ocene','Record review')}</Button>}</>;}},
 ];
 async function saveReview(){if(!review||!onReview||busy)return;const prior=data?.reviews.find(item=>item.connectionId===review.connectionId&&item.stream===review.stream);const fields={connectionId:review.connectionId,stream:review.stream,note,disposition,expectedVersion:prior?.version??0},body=JSON.stringify(fields);if(request.current?.body!==body)request.current={body,id:safeRandomUUID()};setBusy(true);setError(null);try{await onReview({...fields,requestId:request.current.id});setReview(null);}catch(cause){setError(cause instanceof Error?cause.message:'Review failed');}finally{setBusy(false);}}
 return <OperationsFrame title={t('Jakosc danych','Data quality')} description={t('Zbiory, pochodzenie rekordow i wyniki rzeczywistych przebiegow importu.','Datasets, record lineage and results of actual ingestion runs.')} onReload={onReload} demo={demo}>
 <ProductViewNav label={t('Obszary jakosci','Quality sections')} active={view} items={views.map(id=>({id,label:t(...labels[id])}))} onChange={id=>update({qualityView:id})}/>
 <ProductDataState state={state} problem={problem} onRetry={onReload}>{data&&<>
 <p>{t('Odczyt stanu','State read')}: {data.measuredAt}. {t('Czas odczytu nie jest czasem synchronizacji dostawcy.','Read time is not provider synchronization time.')}</p>
 {data.truncated&&<p role="alert">{t('Widok ograniczony do 500 zbiorow lub ocen. Nie jest to kompletna lista.','Limited to 500 datasets or reviews. This is not a complete list.')}</p>}
 {view==='datasets'&&<ProductSectionFrame icon="data" title={t('Zbiory i pokrycie przetwarzania','Datasets and processing coverage')} description={t('Liczniki rekordow nie sa procentem kompletnosci biznesowej. Brak partii nie dowodzi braku sprzedazy.','Record counts are not business completeness percentages. An absent batch does not prove absence of sales.')}><ExplorerTable ariaLabel={t('Zbiory danych','Datasets')} rows={rows} columns={columns} canExport={false} pageSize={20} searchQuery={params.get('qualityQuery')??''} onSearchQueryChange={value=>update({qualityQuery:value||null})} searchText={r=>`${r.provider} ${r.stream} ${r.connectionId}`} onRowClick={r=>update({qualityView:'lineage',qualitySource:r.connectionId,qualityStream:r.stream})}/></ProductSectionFrame>}
 {view==='lineage'&&<ProductSectionFrame icon="data" title={t('Pochodzenie rekordu','Record lineage')}><label>{t('Zbior danych','Dataset')}<select value={selected?.id??''} onChange={e=>{const row=rows.find(item=>item.id===e.target.value);update({qualitySource:row?.connectionId??null,qualityStream:row?.stream??null});}}><option value="">{t('Wybierz zbior','Choose a dataset')}</option>{rows.map(row=><option key={row.id} value={row.id}>{row.provider} / {row.stream} / {row.connectionId.slice(0,8)}</option>)}</select></label>{selected?<><p>{t('Identyfikator polaczenia','Connection id')}: {selected.connectionId}</p>{onSource&&<Button variant="secondary" onClick={()=>onSource(selected.connectionId)}>{t('Otworz synchronizacje zrodla','Open source synchronization')}</Button>}{renderLineage?.(selected)}</>:<p>{t('Wybierz dostepny zbior. Nie wybieramy innego zrodla automatycznie, gdy parametr URL nie pasuje.','Choose an available dataset. A missing URL selection is not silently replaced by another source.')}</p>}</ProductSectionFrame>}
 {view==='reconciliation'&&<ProductSectionFrame icon="data" title={t('Historia rekoncyliacji importu','Ingestion reconciliation history')} description={t('Ostatnie 100 przebiegow potoku. To zgodnosc licznikow przetwarzania, nie automatyczne uzgodnienie sprzedazy miedzy roznymi dostawcami.','Latest 100 pipeline runs. These reconcile processing counts, not automatically sales across different providers.')}>
 {data.runs.length===0?<p>{t('Brak zapisanych przebiegow.','No persisted runs.')}</p>:<div className="pd-operations__table" tabIndex={0}><table><thead><tr><th>{t('Czas','Time')}</th><th>{t('Status','Status')}</th><th>{t('Liczniki / identyfikatory','Counts / identifiers')}</th><th>{t('Zrodlo','Source')}</th></tr></thead><tbody>{data.runs.map(run=><tr key={run.id}><td>{run.createdAt}</td><td>{run.status}</td><td><details><summary>{t('Dowody przebiegu','Run evidence')}</summary><pre>{JSON.stringify(run.details,null,2)}</pre></details></td><td>{onSource&&<Button size="small" variant="ghost" onClick={()=>onSource(run.connectionId)}>{t('Historia zrodla','Source history')}</Button>}</td></tr>)}</tbody></table></div>}
 <p>{t('Ponowienie wykonuje sie dla konkretnego zadania w Integracjach. Ocena reczna nie przelicza ani nie usuwa rekordow.','Retry a specific job in Integrations. A manual review does not recalculate or erase records.')}</p></ProductSectionFrame>}
 {view==='sources'&&<ProductSectionFrame icon="integration" title={t('Nakladanie zrodel i odpowiedzialnosc domen','Overlapping sources and domain ownership')}>
 {[...new Set(rows.map(row=>row.stream))].map(stream=>{const sources=rows.filter(row=>row.stream===stream);return <div key={stream}><h3>{stream}</h3><p>{sources.map(row=>`${row.provider} (${row.connectionId.slice(0,8)})`).join(', ')}</p>{sources.length>1&&<p>{t('Wiele zrodel tego samego strumienia. Sprawdz zakres biznesowy przed sumowaniem; to sygnal do analizy, nie dowod duplikatu.','Multiple sources of this stream. Check business populations before summing; this is a review signal, not proof of duplication.')}</p>}</div>;})}
 <h3>{t('Reguly referencyjne z kontraktu produktu','Reference rules from the product contract')}</h3><p>{t('Reguly sa referencja domenowa. Nie zmieniaja tutaj kolejnosci zrodel ani mapowania rekordow.','These are domain references. This screen does not change source precedence or record mapping.')}</p>{migratedSourcePriorityPolicy.map(rule=><details key={rule.domain}><summary>{rule.domain}</summary><p>{t('Zrodla nadrzedne','Authoritative providers')}: {rule.authoritativeProviders.join(', ')}</p><p>{t('Zrodla uzupelniajace','Fallback providers')}: {rule.fallbackProviders.join(', ')||'--'}</p><pre>{JSON.stringify(rule.fieldOwnership,null,2)}</pre></details>)}
 </ProductSectionFrame>}
 </>}</ProductDataState>
 <OperationsDialog open={review!==null} title={t('Zapis oceny zbioru','Record a dataset review')} busy={busy} onClose={()=>setReview(null)}><p>{review?.provider} / {review?.stream}</p><p>{t('Ocena "resolved" jest oswiadczeniem operatora. Nie uruchamia przetwarzania i nie zastapi statusu rzeczywistego przebiegu.','A "resolved" review is an operator statement. It does not run processing or replace actual run status.')}</p><label>{t('Ocena','Disposition')}<select value={disposition} onChange={e=>setDisposition(e.target.value as QualityReview['disposition'])}><option value="investigating">{t('Analiza w toku','Investigating')}</option><option value="accepted_limitation">{t('Zaakceptowane ograniczenie','Accepted limitation')}</option><option value="resolved">{t('Rozwiazane wedlug operatora','Resolved by operator')}</option></select></label><label>{t('Uzasadnienie i referencja dowodu','Reason and evidence reference')}<textarea value={note} minLength={10} maxLength={4000} onChange={e=>setNote(e.target.value)}/></label><OperationError message={error}/><Button disabled={busy||note.trim().length<10} onClick={()=>void saveReview()}>{t('Potwierdz ocene','Confirm review')}</Button></OperationsDialog>
 </OperationsFrame>;
}
