import { useState } from 'react';
import { Button } from '../../design-system';
import { OperationsDialog, OperationError } from './OperationsFrame';
import { useProductLocale } from '../shared/useProductLocale';
export type IntegrationJobView={id:string;connectionId:string;kind:string;status:string;createdAt:string;attempts:number;errorCode:string|null};
export function integrationJobView(row:Readonly<Record<string,unknown>>):IntegrationJobView{
 if(typeof row.id!=='string'||typeof row.connection_id!=='string'||typeof row.status!=='string')throw new Error('Invalid job response.');
 return {id:row.id,connectionId:row.connection_id,kind:String(row.operation??row.job_type??''),status:row.status,createdAt:String(row.created_at??''),attempts:Number(row.attempts??0),errorCode:typeof row.failure_class==='string'?row.failure_class:null};
}
export function IntegrationJobsPanel({jobs,onCommand,onReload,demo}:{jobs:readonly IntegrationJobView[];onCommand?:(job:IntegrationJobView,action:'retry'|'cancel')=>Promise<void>;onReload?:()=>void;demo?:boolean}){
 const {t}=useProductLocale(),[selected,setSelected]=useState<{job:IntegrationJobView;action:'retry'|'cancel'}|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null);
 async function submit(){if(!selected||!onCommand||busy)return;setBusy(true);setError(null);try{await onCommand(selected.job,selected.action);setNotice(demo?t('Symulacja lokalna.','Local simulation.'):selected.action==='cancel'?t('Zadanie oznaczono do anulowania. Sprawdz koncowy stan workera.','Cancellation requested. Check the final worker state.'):t('Serwer przyjal ponowienie. Sprawdz stan zadania.','Retry accepted by the server. Check the job state.'));setSelected(null);}catch(cause){setError(cause instanceof Error?cause.message:'Job command failed');}finally{setBusy(false);}}
 return <section className="pd-operations"><h2>{t('Operacje synchronizacji','Synchronization operations')}</h2><p>{t('Ostatnie 100 zadan workspace. Pokazano wybrane zrodlo; to nie jest cala historia.','Latest 100 workspace jobs. The selected source is shown; this is not a complete history.')}</p>{onReload&&<Button size="small" variant="secondary" onClick={onReload}>{t('Odswiez zadania','Refresh jobs')}</Button>}{notice&&<p role="status">{notice}</p>}
 {jobs.length===0?<p>{t('Brak zadan w odczytanym zakresie.','No jobs in the retrieved interval.')}</p>:<div className="pd-operations__table" tabIndex={0}><table><thead><tr><th>{t('Zadanie','Job')}</th><th>{t('Status','Status')}</th><th>{t('Czas / proby','Created / attempts')}</th><th>{t('Akcje','Actions')}</th></tr></thead><tbody>{jobs.map(job=><tr key={job.id}><td>{job.kind}<details><summary>{t('Identyfikator','Identifier')}</summary>{job.id}</details></td><td>{job.status}{job.errorCode&&<p>{job.errorCode}</p>}</td><td>{job.createdAt} / {job.attempts}</td><td>{onCommand&&['retryable_failed','failed','dead_lettered','terminal_failed'].includes(job.status)&&<Button size="small" variant="secondary" onClick={()=>{setError(null);setSelected({job,action:'retry'});}}>{t('Ponow','Retry')}</Button>}{onCommand&&['queued','rate_limited','leased','fetching','persisting_source','normalizing','writing_canonical','reconciling','running'].includes(job.status)&&<Button size="small" variant="secondary" onClick={()=>{setError(null);setSelected({job,action:'cancel'});}}>{t('Anuluj','Cancel')}</Button>}</td></tr>)}</tbody></table></div>}
 <OperationsDialog open={selected!==null} busy={busy} title={selected?.action==='cancel'?t('Anulowac zadanie?','Cancel job?'):t('Ponowic zadanie?','Retry job?')} onClose={()=>setSelected(null)}><p>{selected?.job.id}</p><p>{t('Operacja wymaga uprawnien i MFA. Nie cofa juz zapisanych danych; wynik trzeba odczytac z historii.','This requires permissions and MFA. It does not undo persisted data; read the result from history.')}</p><OperationError message={error}/><Button disabled={busy} onClick={()=>void submit()}>{t('Potwierdz','Confirm')}</Button></OperationsDialog>
 </section>;
}
