import { useEffect, useRef, useState } from 'react';
import type { IntegrationProvisionCommand, IntegrationProvisionCapabilities, IntegrationProvisionResult } from '@papadata/contracts';
import type { IntegrationRuntimeCatalogProvider, IntegrationRuntimeSource, IntegrationProviderTestResult } from '../../runtime/integrations/integrationsData';
import { Button } from '../../design-system';
import { safeRandomUUID } from '../../runtime/shared/id/safeRandomUUID';
import { useProductLocale } from '../shared/useProductLocale';
import { OperationsDialog, OperationError } from './OperationsFrame';
type CredentialField={name:string;label:string;secret?:boolean;required?:boolean};
const fields:Record<string,readonly CredentialField[]>={
 woocommerce:[{name:'storeUrl',label:'HTTPS URL',required:true},{name:'consumerKey',label:'Consumer key',secret:true,required:true},{name:'consumerSecret',label:'Consumer secret',secret:true,required:true},{name:'webhookSecret',label:'Webhook secret',secret:true}],
 shopify:[{name:'shopDomain',label:'Shop domain (*.myshopify.com)',required:true},{name:'accessToken',label:'Access token',secret:true,required:true},{name:'apiVersion',label:'API version',required:true},{name:'webhookSecret',label:'Webhook secret',secret:true}],
 baselinker:[{name:'token',label:'API token',secret:true,required:true}],
 google_ads:[{name:'developerToken',label:'Developer token',secret:true,required:true},{name:'customerId',label:'Customer ID',required:true},{name:'loginCustomerId',label:'Manager Customer ID'},{name:'accessToken',label:'Access token',secret:true},{name:'refreshToken',label:'Refresh token',secret:true},{name:'clientId',label:'OAuth client ID'},{name:'clientSecret',label:'OAuth client secret',secret:true},{name:'apiVersion',label:'API version'}],
 meta_ads:[{name:'accountId',label:'Ad account ID',required:true},{name:'accessToken',label:'Access token',secret:true,required:true},{name:'appSecret',label:'App secret',secret:true},{name:'apiVersion',label:'API version'}],
 ga4:[{name:'propertyId',label:'Property ID',required:true},{name:'accessToken',label:'Access token',secret:true},{name:'refreshToken',label:'Refresh token',secret:true},{name:'clientId',label:'OAuth client ID'},{name:'clientSecret',label:'OAuth client secret',secret:true}],
 allegro:[],
};
export type IntegrationConnectDialogProps={provider:IntegrationRuntimeCatalogProvider;source?:IntegrationRuntimeSource;capabilities:IntegrationProvisionCapabilities|null;onClose:()=>void;onTest:(input:Readonly<Record<string,string>>)=>Promise<IntegrationProviderTestResult>;onSave:(input:IntegrationProvisionCommand)=>Promise<IntegrationProvisionResult>;onSaved:(connectionId:string)=>void;demo?:boolean};
export function IntegrationConnectDialog({provider,source,capabilities,onClose,onTest,onSave,onSaved,demo}:IntegrationConnectDialogProps){
 const {t}=useProductLocale(),[step,setStep]=useState<'credentials'|'review'|'done'>('credentials'),[name,setName]=useState(source?.displayName??provider.displayName),[material,setMaterial]=useState<Record<string,string>>({}),[streams,setStreams]=useState<readonly string[]>(source?.selectedStreams??provider.supportedStreams),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[health,setHealth]=useState<IntegrationProviderTestResult|null>(null),[saved,setSaved]=useState<IntegrationProvisionResult|null>(null),request=useRef<{body:string;id:string}|null>(null),mounted=useRef(true);
 useEffect(()=>{mounted.current=true;return()=>{mounted.current=false;};},[]);
 const transportAllowed=demo===true||(typeof window!=='undefined'&&window.isSecureContext);
 const permitted=provider.connectable&&provider.provider!=='allegro'&&!(provider.provider==='baselinker'&&source)&&capabilities?.enabled===true&&transportAllowed;
 function close(){if(busy)return;if(Object.values(material).some(Boolean)&&step!=='done'&&!window.confirm(t('Odrzucić niezapisane dane połączenia?','Discard unsaved connection details?')))return;setMaterial({});onClose();}
 async function verify(){if(!permitted||busy)return;setBusy(true);setError(null);setHealth(null);try{const result=await onTest(material);if(!mounted.current)return;setHealth(result);if(result.canSave)setStep('review');}catch(cause){if(mounted.current)setError(cause instanceof Error?cause.message:'Provider verification failed');}finally{if(mounted.current)setBusy(false);}}
 async function save(){if(!health?.canSave||busy||!permitted)return;const input={provider:provider.provider,displayName:name,streams,material,expectedVersion:source?.credentialVersion??0,...(source?{connectionId:source.integrationId}:{})},body=JSON.stringify(input);if(request.current?.body!==body)request.current={body,id:safeRandomUUID()};setBusy(true);setError(null);try{const result=await onSave({...input,requestId:request.current.id});if(!mounted.current)return;setSaved(result);setMaterial({});setStep('done');}catch(cause){if(mounted.current)setError(cause instanceof Error?cause.message:'Credential provisioning failed');}finally{if(mounted.current)setBusy(false);}}
 return <OperationsDialog open title={`${source?t('Połącz ponownie','Reconnect'):t('Połącz źródło','Connect source')} / ${provider.displayName}`} busy={busy} onClose={close}>
 {demo&&<p role="alert">{t('Demonstracja: nie wpisuj prawdziwych danych dostępu.','Demonstration: do not enter real credentials.')}</p>}
 <p>{t('Dane dostępu trafiają do serwera przez HTTPS, a następnie do Google Secret Manager. Nie zapisujemy ich w URL ani konfiguracji projektu.','Credentials are sent over HTTPS to the server and then Google Secret Manager. They are not stored in URL or project configuration.')}</p>
 {!transportAllowed&&<p role="alert">{t('Niezabezpieczony adres IP służy tylko do podglądu. Do wysyłania sekretów użyj HTTPS lub lokalnego bezpiecznego kontekstu.','An insecure IP address is read-only. Use HTTPS or a local secure context before submitting credentials.')}</p>}
 {!capabilities?.enabled&&<p role="alert">{capabilities?.reason??t('Nie odczytano konfiguracji magazynu sekretów.','Secret storage configuration was not read.')}</p>}
 {provider.authType==='oauth'&&<p>{t('Formularz przyjmuje już wydany token konta. Nie udaje przekierowania ani zgody OAuth. Tokeny i uprawnienia nadaj w aplikacji dostawcy.','This form accepts an already issued account token. It does not simulate an OAuth redirect or consent. Issue tokens and permissions in the provider application.')}</p>}
 {!provider.connectable||provider.provider==='allegro'||provider.provider==='baselinker'&&source?<p role="alert">{t('Ten wariant wymaga konfiguracji lub adaptera potwierdzania tożsamości konta. Zapis jest zablokowany.','This variant requires configuration or an account-identity adapter. Saving is blocked.')}</p>:null}
 <OperationError message={error}/>
 {step==='credentials'&&<form onSubmit={e=>{e.preventDefault();void verify();}} className="pd-operations__form"><label>{t('Nazwa źródła','Source label')}<input value={name} required maxLength={160} disabled={busy} onChange={e=>setName(e.target.value)}/></label>
 {(fields[provider.provider]??[]).map(field=><label key={field.name}>{field.label}<input name={`credential-${field.name}`} type={field.secret?'password':'text'} autoComplete="off" spellCheck={false} value={material[field.name]??''} maxLength={4096} required={field.required} disabled={busy||!permitted} onChange={e=>{setHealth(null);setMaterial(v=>({...v,[field.name]:e.target.value}));}}/></label>)}
 <fieldset disabled={busy||!permitted}><legend>{t('Strumienie do synchronizacji','Synchronization streams')}</legend>{provider.supportedStreams.map(stream=><label key={stream} className="pd-operations__check"><input type="checkbox" checked={streams.includes(stream)} onChange={()=>setStreams(current=>current.includes(stream)?current.filter(v=>v!==stream):[...current,stream])}/>{stream}</label>)}</fieldset>
 <p>{t('Wymagania uprawnień dostawcy','Provider permission requirements')}: {provider.requiredScopes.join(', ')||t('Według konfiguracji konta','According to account configuration')}. {t('Wybieranie strumieni nie nadaje uprawnień OAuth.','Selecting streams does not grant OAuth scopes.')}</p>
 {health&&!health.canSave&&<p role="alert">{health.formValidation.message} {health.providerTest.message}</p>}
 <Button type="submit" disabled={busy||!permitted||streams.length===0}>{busy?t('Weryfikacja','Verifying'):t('Sprawdź dane u dostawcy','Verify with the provider')}</Button></form>}
 {step==='review'&&<><h3>{t('Przegląd połączenia','Connection review')}</h3><p>{name} / {provider.displayName}</p><p>{streams.join(', ')}</p><p>{t('Test potwierdza dostęp do punktu weryfikacji, nie kompletność historii ani wszystkich uprawnień. Przy zapisie serwer ponownie weryfikuje dane.','The check confirms access to a verification endpoint, not full history or every permission. The server verifies credentials again before saving.')}</p>{source&&<p>{t('Zastąpisz dane dostępu tylko tej integracji. Zmiana konta dostawcy przez ponowną autoryzację jest zablokowana.','Only this integration is reauthorized. Changing the provider account through reconnect is blocked.')}</p>}
 <div className="pd-operations__actions"><Button variant="secondary" disabled={busy} onClick={()=>setStep('credentials')}>{t('Wróć do formularza','Back to form')}</Button><Button disabled={busy||!permitted} onClick={()=>void save()}>{t('Potwierdź zapis w Secret Manager','Confirm Secret Manager storage')}</Button></div></>}
 {step==='done'&&saved&&<><p role="status">{demo?t('Demo: symulacja połączenia, bez dostawcy i bez zapisu sekretu.','Demo: simulated connection, without provider access or secret storage.'):t('Połączenie zapisane i zweryfikowane przez serwer.','Connection persisted and verified by the server.')}</p><p>{t('Nie uruchomiono synchronizacji. Otwórz źródło i zleć pobranie danych; wynik zobaczysz w historii.','Synchronization was not started. Open the source and request an import; check its result in history.')}</p><Button onClick={()=>{onSaved(saved.connectionId);onClose();}}>{t('Otwórz źródło','Open source')}</Button></>}
 </OperationsDialog>;
}
