import { useRef, useState } from 'react';
import type { PlatformPrivacyRequest } from '@papadata/contracts';
import { Button, ProductSectionFrame } from '../../design-system';
import { safeRandomUUID } from '../../runtime/shared/id/safeRandomUUID';
import { useProductLocale } from '../shared/useProductLocale';
import { OperationsDialog, OperationError } from './OperationsFrame';
export function SettingsPrivacyPanel({requests,onCreate}:{requests:readonly PlatformPrivacyRequest[];onCreate?:(input:{requestId:string;subjectReference:string;requestType:'export'|'deletion'})=>Promise<void>}){
 const {t}=useProductLocale(),[open,setOpen]=useState(false),[subject,setSubject]=useState(''),[kind,setKind]=useState<'export'|'deletion'>('export'),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),request=useRef<{body:string;id:string}|null>(null);
 return <ProductSectionFrame icon="security" title={t('Prywatnosc i realizacja wnioskow','Privacy requests')} description={t('Wniosek nie oznacza wykonanego eksportu ani usuniecia danych. Obowiazuja weryfikacja tozsamosci, akceptacja i dowody wykonania.','A request does not mean export or erasure is complete. Identity verification, approval and execution evidence are required.')}>
 <p>{t('Ostatnie 100 wnioskow tego workspace. Status czesciowy nie oznacza pelnego wykonania.','Latest 100 requests in this workspace. Partial status does not mean completed execution.')}</p>{onCreate&&<Button onClick={()=>{setOpen(true);setError(null);}}>{t('Nowy wniosek','New request')}</Button>}
 {requests.length===0?<p>{t('Brak wnioskow.','No requests.')}</p>:<div className="pd-operations__table"><table><thead><tr><th>{t('Wniosek','Request')}</th><th>{t('Typ','Type')}</th><th>{t('Status','Status')}</th><th>{t('Termin','Due')}</th><th>{t('Systemy','Systems')}</th></tr></thead><tbody>{requests.map(row=><tr key={row.id}><td>{row.id}<br/>{row.subject}</td><td>{row.kind}</td><td>{row.status}{row.legalHold?' / legal hold':''}</td><td>{row.dueAt}</td><td>{row.targets.map(target=><p key={target.system}>{target.system}: {target.status} {target.errorCode??''}</p>)}</td></tr>)}</tbody></table></div>}
 <OperationsDialog open={open} title={t('Zarejestruj wniosek','Register request')} busy={busy} onClose={()=>setOpen(false)}><label>{t('Referencja osoby w systemie','Subject reference')}<input value={subject} minLength={1} maxLength={500} onChange={e=>setSubject(e.target.value)}/></label><label>{t('Typ wniosku','Request type')}<select value={kind} onChange={e=>setKind(e.target.value==='deletion'?'deletion':'export')}><option value="export">{t('Eksport','Export')}</option><option value="deletion">{t('Usuniecie','Erasure')}</option></select></label><p>{t('Zapis zarejestruje wniosek do weryfikacji. Nie usuwa danych natychmiast i nie generuje automatycznie pliku.','Saving registers a request for verification. It does not erase data immediately or automatically generate a file.')}</p><OperationError message={error}/><Button disabled={busy||!subject.trim()} onClick={()=>{if(!onCreate)return;const body=JSON.stringify({subject,kind});if(request.current?.body!==body)request.current={body,id:safeRandomUUID()};setBusy(true);void onCreate({requestId:request.current.id,subjectReference:subject,requestType:kind}).then(()=>{setOpen(false);setSubject('');}).catch(cause=>setError(cause instanceof Error?cause.message:'Operation failed')).finally(()=>setBusy(false));}}>{t('Zarejestruj','Register')}</Button></OperationsDialog>
 </ProductSectionFrame>;
}
