import { useRef, useState } from 'react';
import { assignableTeamRoles, type TeamOverview, type TeamMember, type MemberCommand } from '@papadata/contracts';
import { Button, ProductSectionFrame } from '../../design-system';
import { safeRandomUUID } from '../../runtime/shared/id/safeRandomUUID';
import { useProductLocale } from '../shared/useProductLocale';
import { OperationsDialog, OperationError } from './OperationsFrame';
export type SettingsTeamPanelProps={data:TeamOverview;onInvite?:(email:string,role:string)=>Promise<void>;onCancelInvitation?:(id:string)=>Promise<void>;onMember?:(id:string,command:MemberCommand)=>Promise<void>};
export function SettingsTeamPanel({data,onInvite,onCancelInvitation,onMember}:SettingsTeamPanelProps){
 const {t}=useProductLocale(),[email,setEmail]=useState(''),[role,setRole]=useState<string>('Viewer'),[target,setTarget]=useState<TeamMember|null>(null),[action,setAction]=useState<'role'|'revoke'>('role'),[nextRole,setNextRole]=useState('Viewer'),[reason,setReason]=useState(''),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null),[notice,setNotice]=useState<string|null>(null),[cancel,setCancel]=useState<string|null>(null);
 const request=useRef<{body:string;id:string}|null>(null);
 async function run(operation:()=>Promise<void>,message:string){if(busy)return;setBusy(true);setError(null);setNotice(null);try{await operation();setNotice(message);setTarget(null);setCancel(null);}catch(cause){setError(cause instanceof Error?cause.message:t('Operacja nie powiodla sie','Operation failed'));}finally{setBusy(false);}}
 async function submitMember(){if(!target||!onMember)return;const body=JSON.stringify({id:target.id,action,role:nextRole,reason,version:target.version});if(request.current?.body!==body)request.current={body,id:safeRandomUUID()};await run(()=>onMember(target.id,{requestId:request.current!.id,expectedVersion:target.version,action,...(action==='role'?{role:nextRole}:{}),reason}),t('Zmiana dostepu zapisana.','Access change saved.'));}
 return <ProductSectionFrame icon="customers" title={t('Zespol i zaproszenia','Team and invitations')} description={t('Zmiany obejmuja wybrany workspace. Wlasnosc i czasowy dostep wsparcia wymagaja osobnej procedury.','Changes affect this workspace. Ownership and temporary support access require separate procedures.')}>
 <OperationError message={error}/>{notice&&<p role="status">{notice}</p>}
 <div className="pd-operations__table"><table><caption>{t('Czlonkowie workspace','Workspace members')}</caption><thead><tr><th>{t('Osoba','Person')}</th><th>{t('Rola / zakres','Role / scope')}</th><th>MFA</th><th>{t('Status','Status')}</th><th>{t('Akcje','Actions')}</th></tr></thead><tbody>{data.members.map(member=><tr key={member.id}><td>{member.name}<br/>{member.email}</td><td>{member.role}<br/>{member.scope}</td><td>{member.mfaEnabled?t('Wlaczone','Enabled'):t('Wylaczone','Disabled')}</td><td>{member.status}</td><td>{data.canManage&&onMember&&member.userId!==data.currentUserId&&member.status==='active'&&!['Tenant Owner','Internal Support/Operations'].includes(member.role)?<div className="pd-operations__actions"><Button size="small" variant="secondary" onClick={()=>{setTarget(member);setAction('role');setNextRole(member.role);setReason('');setError(null);}}>{t('Zmien role','Change role')}</Button><Button size="small" variant="ghost" onClick={()=>{setTarget(member);setAction('revoke');setReason('');setError(null);}}>{t('Odbierz dostep','Revoke access')}</Button></div>:t('Brak dostepnej zmiany','No available change')}</td></tr>)}</tbody></table></div>
 {data.canManage&&onInvite&&<form className="pd-operations__form" onSubmit={e=>{e.preventDefault();void run(async()=>{await onInvite(email,role);setEmail('');},t('Zaproszenie utworzone; status dostarczenia nie jest tu potwierdzany.','Invitation created; delivery is not confirmed here.'));}}><h3>{t('Zapros nowa osobe','Invite a person')}</h3><label>E-mail<input required type="email" maxLength={254} value={email} onChange={e=>setEmail(e.target.value)}/></label><label>{t('Rola','Role')}<select value={role} onChange={e=>setRole(e.target.value)}>{assignableTeamRoles.map(value=><option key={value}>{value}</option>)}</select></label><Button type="submit" disabled={busy}>{t('Utworz zaproszenie','Create invitation')}</Button></form>}
 <h3>{t('Oczekujace zaproszenia','Pending invitations')}</h3>{data.invitations.length===0?<p>{t('Brak oczekujacych zaproszen.','No pending invitations.')}</p>:<div className="pd-operations__table"><table><thead><tr><th>E-mail</th><th>{t('Rola','Role')}</th><th>{t('Wazne do','Expires')}</th><th>{t('Akcja','Action')}</th></tr></thead><tbody>{data.invitations.map(invitation=><tr key={invitation.id}><td>{invitation.email}</td><td>{invitation.role}</td><td>{invitation.expiresAt}{Date.parse(invitation.expiresAt)<Date.now()?` / ${t('wygasle','expired')}`:''}</td><td>{data.canManage&&onCancelInvitation&&<Button size="small" variant="ghost" onClick={()=>setCancel(invitation.id)}>{t('Uniewaznij','Revoke')}</Button>}</td></tr>)}</tbody></table></div>}
 <OperationsDialog open={target!==null} title={action==='role'?t('Zmiana roli','Role change'):t('Odebranie dostepu','Revoke access')} busy={busy} onClose={()=>setTarget(null)}><p>{target?.name} / {target?.email}</p>{action==='role'&&<label>{t('Nowa rola','New role')}<select value={nextRole} onChange={e=>setNextRole(e.target.value)}>{assignableTeamRoles.map(value=><option key={value}>{value}</option>)}</select></label>}<label>{t('Uzasadnienie (minimum 10 znakow)','Reason (at least 10 characters)')}<textarea value={reason} minLength={10} maxLength={1000} onChange={e=>setReason(e.target.value)}/></label><OperationError message={error}/><Button disabled={busy||reason.trim().length<10} onClick={()=>void submitMember()}>{t('Potwierdz zmiane','Confirm change')}</Button></OperationsDialog>
 <OperationsDialog open={cancel!==null} title={t('Uniewaznic zaproszenie?','Revoke invitation?')} busy={busy} onClose={()=>setCancel(null)}><p>{t('Zaproszenie przestanie umozliwiac uzyskanie dostepu.','This invitation will no longer grant access.')}</p><OperationError message={error}/><Button disabled={busy} onClick={()=>{if(cancel&&onCancelInvitation)void run(()=>onCancelInvitation(cancel),t('Zaproszenie uniewaznione.','Invitation revoked.'));}}>{t('Potwierdz','Confirm')}</Button></OperationsDialog>
 </ProductSectionFrame>;
}
