import { useState } from 'react';
import { Button, ProductSectionFrame } from '../../design-system';
import type { BffSessionSummary } from '../../runtime/shared/api/bffClient';
import { useProductLocale } from '../shared/useProductLocale';
import { OperationError, OperationsDialog } from './OperationsFrame';
export function SettingsSecurityPanel({sessions,mfaEnabled,onRevoke,onConfigureMfa,onDisableMfa}:{sessions:readonly BffSessionSummary[];mfaEnabled:boolean;onRevoke?:(id:string)=>Promise<void>;onConfigureMfa?:()=>void;onDisableMfa?:()=>Promise<void>}){
 const {t}=useProductLocale(),[disable,setDisable]=useState(false),[target,setTarget]=useState<BffSessionSummary|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState<string|null>(null);
 return <ProductSectionFrame icon="security" title={t('Bezpieczeństwo konta','Account security')} description={t('Sesje dotyczą Twojego konta, nie wszystkich członków organizacji.','Sessions belong to your account, not to every member of the organization.')}>
 <p>MFA: {mfaEnabled?t('włączone','enabled'):t('wyłączone','disabled')}</p>{onConfigureMfa&&<Button variant="secondary" onClick={onConfigureMfa}>{t('Otwórz konfigurację MFA','Open MFA setup')}</Button>}
 {mfaEnabled&&onDisableMfa&&<Button variant="secondary" onClick={()=>{setDisable(true);setError(null);}}>{t('Wyłącz MFA','Disable MFA')}</Button>}
 <p>{t('Kody odzyskiwania są jednorazowe i pokazywane tylko podczas konfiguracji. Ten widok nie odtwarza utraconych kodów ani nie omija potwierdzenia tożsamości.','Recovery codes are single-use and shown only during enrollment. This screen cannot recover lost codes or bypass identity verification.')}</p>
 <div className="pd-operations__table" tabIndex={0}><table><caption>{t('Aktywne sesje','Active sessions')}</caption><thead><tr><th>{t('Sesja','Session')}</th><th>{t('Urządzenie','Device')}</th><th>{t('Utworzona','Issued')}</th><th>{t('Ważna do','Expires')}</th><th>{t('Akcja','Action')}</th></tr></thead><tbody>{sessions.map(session=><tr key={session.sessionId}><td>{session.current?t('Bieżąca sesja','Current session'):session.sessionId.slice(0,8)}</td><td>{session.userAgent??t('Brak informacji','Not available')}</td><td>{session.issuedAt}</td><td>{session.expiresAt}</td><td>{onRevoke&&<Button size="small" variant="ghost" onClick={()=>{setTarget(session);setError(null);}}>{t('Unieważnij','Revoke')}</Button>}</td></tr>)}</tbody></table></div>
 <OperationsDialog open={target!==null} title={t('Unieważnić sesję?','Revoke session?')} busy={busy} onClose={()=>setTarget(null)}><p>{target?.current?t('Ta operacja wyloguje Cię z bieżącej sesji.','This will sign you out of the current session.'):t('Wybrane urządzenie utraci dostęp.','The selected device will lose access.')}</p><OperationError message={error}/><Button disabled={busy} onClick={()=>{if(!target||!onRevoke)return;setBusy(true);void onRevoke(target.sessionId).then(()=>setTarget(null)).catch(cause=>setError(cause instanceof Error?cause.message:'Operation failed')).finally(()=>setBusy(false));}}>{t('Potwierdź','Confirm')}</Button></OperationsDialog>
 <OperationsDialog open={disable} title={t('Wyłączyć MFA i zakończyć sesje?','Disable MFA and end sessions?')} busy={busy} onClose={()=>setDisable(false)}><p>{t('Wymagane jest ponowne uwierzytelnienie. Po potwierdzeniu wszystkie sesje konta zostaną unieważnione, także ta sesja.','Reauthentication is required. Confirmation revokes every account session, including this one.')}</p><OperationError message={error}/><Button disabled={busy} onClick={()=>{if(!onDisableMfa)return;setBusy(true);setError(null);void onDisableMfa().then(()=>setDisable(false)).catch(cause=>setError(cause instanceof Error?cause.message:'MFA change failed')).finally(()=>setBusy(false));}}>{t('Potwierdź wyłączenie','Confirm disable')}</Button></OperationsDialog>
 </ProductSectionFrame>;
}
