-- Deprecated compatibility marker.
-- Production and production-parity roles are provisioned before migrations by
-- an administrative bootstrap process. No credentials are stored in SQL.
-- See infra/postgres/init/01-create-production-parity-roles.sh and
-- docs/backend-remediation/MIGRATION-AND-DR.md.
