import type {ReactNode} from 'react';
import {useEffect,useState} from 'react';
import {accessSurfaces,isValidNip,type AccessSurfaceId,type AccessLifecycleStatus,type CompanyProfile} from '@papadata/contracts';
import {Button} from '../../../design-system';
import {useProductLocale} from '../../../screens/shared/useProductLocale';
import {AuthRuntimePreferences} from './AuthRuntimePreferences';
import './access-lifecycle.css';
export type AccessFlowAction='retry'|'verify'|'resend'|'company'|'company-lookup'|'consents'|'complete'|'logout'|'mfa';
export type AccessFlowProps={children?:ReactNode;surface:AccessSurfaceId;data?:AccessLifecycleStatus|null;problem?:string|null;notice?:string|null;busy?:boolean;loading?:boolean;demo?:boolean;hasToken?:boolean;companyLookup?:{readonly normalized:CompanyProfile}|null;companyLookupProblem?:string|null;onAction:(action:AccessFlowAction,input?:unknown)=>void;onNavigate:(path:string)=>void};
export function AccessFlowScreen({children,surface,data=null,problem=null,notice=null,busy=false,loading=false,demo=false,hasToken=false,companyLookup=null,companyLookupProblem=null,onAction,onNavigate}:AccessFlowProps){
 const {t,locale}=useProductLocale(),definition=accessSurfaces.find(x=>x[0]===surface)!,title=locale==='en'?definition[2]:definition[1];
 const [company,updateCompany]=useState<CompanyProfile>(()=>data?.company?.values??{legalName:'',vatId:'',street:'',city:'',postalCode:'',country:'PL'});
 const [accepted,setAccepted]=useState<string[]>([]),[email,setEmail]=useState(data?.email??''),[nipQuery,setNipQuery]=useState('');
 useEffect(()=>{if(data?.company)updateCompany(data.company.values);if(data?.email)setEmail(data.email);},[data?.company?.version,data?.email]);
 // company.lookup's result comes back through the parent (AccessRouter),
 // not this component -- see DOC-P0-005 task 5. Prefilling here reuses the
 // exact same `company` state and onAction('company',...) save path as the
 // existing manual form; the user still lands on auth-07/auth-10 to review
 // and, if needed, correct it before saving.
 useEffect(()=>{if(companyLookup)updateCompany(companyLookup.normalized);},[companyLookup]);
 useEffect(()=>{document.getElementById('access-title')?.focus();},[surface]);
 const done=(id:string)=>data?.acceptedDocuments.some(x=>x.id===id&&data.documents.some(d=>d.id===id&&d.version===x.version))??false;
 const enabled=!busy&&!loading;
 return <main className="pd-access" data-auth-surface={surface} aria-busy={busy||loading}>
 <header className="pd-access__header"><a href="/auth" onClick={e=>{e.preventDefault();onNavigate('/auth');}} className="pd-access__brand">PapaData</a><AuthRuntimePreferences/></header>
 <div className="pd-access__layout"><aside className="pd-access__context"><p className="pd-access__eyebrow">{t('Dostep do workspace','Workspace access')}</p><h2>{t('Od konta do pierwszych danych.','From an account to your first data.')}</h2><p>{t('Kazdy etap ma jawny wynik. Sekrety pozostaja tylko w pamieci formularza.','Every step has an explicit result. Form secrets stay in memory only.')}</p><ol className="pd-access__steps">{[
  [t('Potwierdz e-mail','Verify email'),data?.emailVerified], [t('Dane firmy','Company details'),!!data?.company], [t('Dokumenty i zgody','Documents and consent'),!!data?.documentsConfigured&&data.documents.every(d=>done(d.id))], [t('Pierwsze dane','First data'),(data?.readySourceCount??0)>0],
 ].map(([label,ok],i)=><li key={i} data-complete={Boolean(ok)}><span aria-hidden="true">{ok?'OK':i+1}</span>{label}</li>)}</ol><p className="pd-access__hint">{t('Dane firmy sa wspolne dla workspace. Potwierdzenia dokumentow przypisujemy do uzytkownika i wersji.','Company details belong to the workspace. Acknowledgements belong to the user and document version.')}</p></aside>
 <section className="pd-access__panel" aria-labelledby="access-title"><p className="pd-access__eyebrow">{demo?t('Scenariusz demonstracyjny','Demonstration scenario'):'PapaData / Access'}</p><h1 id="access-title" tabIndex={-1}>{title}</h1>
 {loading?<p role="status">{t('Wczytywanie aktualnego stanu...','Loading current status...')}</p>:null}
 {problem?<div role="alert" className="pd-access__error"><p>{problem}</p><Button variant="secondary" disabled={busy} onClick={()=>onAction('retry')}>{t('Ponow odczyt','Retry read')}</Button></div>:null}
 {notice?<p role="status" className="pd-access__notice">{notice}</p>:null}
 {surface==='auth-06'?<><p>{data?.emailVerified?t('Adres zostal potwierdzony.','Email verified.'):t('Otworz wiadomosc i potwierdz adres. Link jest jednorazowy i wygasa.','Open the message and verify your address. The link is single-use and expires.')}</p>{hasToken?<Button disabled={!enabled} onClick={()=>onAction('verify')}>{t('Potwierdz adres z linku','Verify using this link')}</Button>:null}<label>{t('Adres e-mail','Email address')}<input type="email" autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)} /></label><div className="pd-access__actions"><Button variant="secondary" disabled={!enabled||!email||data?.emailVerified} onClick={()=>onAction('resend',{email})}>{t('Wyslij nowy link','Send a new link')}</Button><Button disabled={!enabled||!data?.emailVerified} onClick={()=>onNavigate('/auth/company')}>{t('Dalej: firma','Next: company')}</Button></div><p>{t('Po odswiezeniu ponownie otworz link z wiadomosci. Jesli zostal wykorzystany, zaloguj sie i odswiez stan.','After refreshing, reopen the email link. If already consumed, sign in and refresh the status.')}</p></>:null}
 {['auth-07','auth-10'].includes(surface)?<form onSubmit={e=>{e.preventDefault();if(enabled&&isValidNip(company.vatId))onAction('company',{values:company,expectedVersion:data?.company?.version??0,prefilledFromLookup:!!companyLookup&&JSON.stringify(company)===JSON.stringify(companyLookup.normalized)});}}><p>{t('Dane podane recznie nie sa potwierdzeniem wpisu w rejestrze ani uprawnien do organizacji.','Manual details do not verify a registry entry or ownership of an organization.')}</p>{companyLookup?<p role="status">{t('Dane pobrane z GUS/BIR. Sprawdz je przed zapisem -- kazda zmiana pola oznacza wpis reczny.','Data fetched from GUS/BIR. Review it before saving -- changing any field marks it as a manual entry.')}</p>:null}<fieldset disabled={!enabled||!data?.canEditCompany}>
 <label>{t('Nazwa firmy','Legal company name')}<input required autoComplete="organization" maxLength={200} value={company.legalName} onChange={e=>updateCompany({...company,legalName:e.target.value})}/></label>
 <label>NIP<input required inputMode="numeric" maxLength={20} value={company.vatId} aria-invalid={!!company.vatId&&!isValidNip(company.vatId)} onChange={e=>updateCompany({...company,vatId:e.target.value})}/></label>{company.vatId&&!isValidNip(company.vatId)?<p>{t('Sprawdz 10 cyfr i sume kontrolna NIP.','Check the 10 digits and NIP checksum.')}</p>:null}
 <label>{t('Ulica i numer','Street and number')}<input required autoComplete="street-address" maxLength={200} value={company.street} onChange={e=>updateCompany({...company,street:e.target.value})}/></label><div className="pd-access__fields"><label>{t('Kod pocztowy','Postal code')}<input required autoComplete="postal-code" pattern="[0-9]{2}-?[0-9]{3}" value={company.postalCode} onChange={e=>updateCompany({...company,postalCode:e.target.value})}/></label><label>{t('Miasto','City')}<input required autoComplete="address-level2" maxLength={120} value={company.city} onChange={e=>updateCompany({...company,city:e.target.value})}/></label></div><Button type="submit" disabled={!isValidNip(company.vatId)}>{t('Zapisz i przejrzyj dane','Save and review')}</Button></fieldset>{data&&!data.canEditCompany?<p role="status">{t('Dane firmy zmienia administrator workspace.','A workspace administrator must update company details.')}</p>:null}</form>:null}
 {surface==='auth-08'?<><p role={companyLookupProblem?'alert':undefined}>{companyLookupProblem??t('Wpisz NIP, aby automatycznie pobrac dane firmy z rejestru GUS/BIR. Bedzie mozna je poprawic przed zapisem.','Enter a NIP to automatically fetch company details from the GUS/BIR registry. You can correct the data before saving.')}</p><label>NIP<input inputMode="numeric" maxLength={20} value={nipQuery} aria-invalid={!!nipQuery&&!isValidNip(nipQuery)} onChange={e=>setNipQuery(e.target.value)}/></label>{nipQuery&&!isValidNip(nipQuery)?<p>{t('Sprawdz 10 cyfr i sume kontrolna NIP.','Check the 10 digits and NIP checksum.')}</p>:null}<div className="pd-access__actions"><Button disabled={!enabled||!isValidNip(nipQuery)} onClick={()=>onAction('company-lookup',{nip:nipQuery})}>{busy?t('Szukanie...','Searching...'):t('Szukaj w GUS/BIR','Search GUS/BIR')}</Button><Button variant="secondary" onClick={()=>onNavigate('/auth/company/manual')}>{t('Wprowadz dane recznie','Enter details manually')}</Button></div></>:null}
 {surface==='auth-09'||surface==='auth-11'?<><p>{!data?.company?t('Brak zapisanego profilu firmy.','No saved company profile.'):surface==='auth-11'?t('Ten workspace ma juz profil firmy. Nie wyszukujemy cudzych kont po NIP.','This workspace has a company profile. Other accounts are not exposed by tax number.'):t('Sprawdz dane zapisane na serwerze.','Review the saved details.')}</p>{data?.company?<dl className="pd-access__details"><dt>{t('Firma','Company')}</dt><dd>{data.company.values.legalName}</dd><dt>NIP</dt><dd>{data.company.values.vatId}</dd><dt>{t('Adres','Address')}</dt><dd>{data.company.values.street}, {data.company.values.postalCode} {data.company.values.city}</dd><dt>{t('Zrodlo / wersja','Source / version')}</dt><dd>{t('Wpis reczny','Manual entry')} / {data.company.version}</dd></dl>:null}<div className="pd-access__actions"><Button variant="secondary" onClick={()=>onNavigate('/auth/company/manual')}>{t('Edytuj','Edit')}</Button><Button disabled={!data?.company} onClick={()=>onNavigate('/auth/consents')}>{t('Dalej','Continue')}</Button></div></>:null}
 {surface==='auth-12'?<form onSubmit={e=>{e.preventDefault();if(enabled&&data?.documentsConfigured&&data.documents.every(d=>accepted.includes(d.id)||done(d.id)))onAction('consents',{documents:data.documents.map(d=>({id:d.id,version:d.version}))});}}><p>{t('Przeczytaj wskazane wersje dokumentow. Pola nie sa zaznaczane automatycznie.','Read the document versions. Checkboxes are not selected automatically.')}</p>{!data?.documentsConfigured?<p role="status">{t('Administrator musi skonfigurowac zatwierdzone dokumenty i ich wersje. Nie mozna zaakceptowac brakujacego regulaminu.','Approved document URLs and versions must be configured. Missing terms cannot be accepted.')}</p>:data.documents.map(d=><label className="pd-access__check" key={`${d.id}:${d.version}`}><input type="checkbox" checked={done(d.id)||accepted.includes(d.id)} disabled={!enabled||done(d.id)} onChange={e=>setAccepted(a=>e.target.checked?[...a,d.id]:a.filter(x=>x!==d.id))}/><span>{d.id==='terms'?t('Akceptuje regulamin','I accept the terms'):t('Potwierdzam zapoznanie sie z informacja o prywatnosci','I have read the privacy notice')} <a href={d.url} target="_blank" rel="noopener noreferrer">{t('wersja','version')} {d.version}</a></span></label>)}<Button disabled={!enabled||!data?.documentsConfigured||!data.documents.every(d=>done(d.id)||accepted.includes(d.id))} type="submit">{t('Zapisz potwierdzenia','Save acknowledgements')}</Button></form>:null}
 {surface==='auth-13'?<><p>{t('Zakonczenie wymaga potwierdzonego e-maila, danych firmy i aktualnych dokumentow.','Completion requires verified email, company details and current documents.')}</p><Button disabled={!enabled} onClick={()=>onAction('complete')}>{busy?t('Zapisywanie...','Saving...'):t('Zakoncz przygotowanie konta','Complete account setup')}</Button></>:null}
 {surface==='auth-14'||surface==='auth-29'?<><p>{data?.completedAt?t('Przygotowanie konta zapisane. Teraz polacz pierwsze zrodlo.','Account setup is saved. Connect your first source.'):t('Dokoncz przygotowanie konta. Stan kazdego kroku odczytujemy z serwera.','Complete account setup. Each step reflects server state.')}</p><div className="pd-access__actions">{!data?.emailVerified?<Button onClick={()=>onNavigate('/auth/verify-email')}>{t('Potwierdz e-mail','Verify email')}</Button>:!data?.company?<Button onClick={()=>onNavigate('/auth/company')}>{t('Uzupelnij firme','Add company details')}</Button>:!data?.completedAt?<Button onClick={()=>onNavigate('/auth/consents')}>{t('Przejdz do dokumentow','Review documents')}</Button>:null}<Button variant="secondary" onClick={()=>onNavigate('/auth/mfa/setup')}>{t('Zabezpiecz konto MFA','Secure account with MFA')}</Button><Button disabled={!data?.completedAt} onClick={()=>onNavigate('/app/integrations')}>{t('Polacz zrodlo','Connect a source')}</Button><Button variant="secondary" onClick={()=>onAction('retry')}>{t('Odswiez stan','Refresh status')}</Button></div><dl className="pd-access__details"><dt>{t('Polaczenia','Connections')}</dt><dd>{data?.integrationCount??'--'}</dd><dt>{t('Zrodla z rekordami','Sources with imported records')}</dt><dd>{data?.readySourceCount??'--'}</dd><dt>{t('Ostatnie zakonczenie synchronizacji','Last sync completion')}</dt><dd>{data?.lastSyncAt??t('Brak potwierdzenia','Not confirmed')}</dd></dl><p>{t('Zaimportowane rekordy nie potwierdzaja kompletnosci wszystkich metryk.','Imported records do not prove completeness of every metric.')}</p><Button onClick={()=>onNavigate('/app/command-center')}>{t('Przejdz do aplikacji','Open application')}</Button></>:null}
 {surface==='auth-17'?<><p>{t('Sekret i kody odzyskiwania pokazemy tylko w biezacym oknie.','Secret and recovery codes are only displayed in the current window.')}</p><Button disabled={!enabled} onClick={()=>onAction('mfa')}>{t('Skonfiguruj MFA','Set up MFA')}</Button></>:null}
 {surface==='auth-19'?<><p role="status">{t('Jezeli konto spelnia warunki odzyskiwania, wiadomosc zostanie wyslana. Zlecenie wysylki nie potwierdza doreczenia.','If the account is eligible, recovery instructions will be sent. Queueing is not proof of delivery.')}</p><Button onClick={()=>onNavigate('/login')}>{t('Wroc do logowania','Back to sign in')}</Button></>:null}
 {surface==='auth-25'?<><p>{t('Wylogowanie konczy biezaca sesje.','Signing out ends this session.')}</p><Button disabled={!enabled} onClick={()=>onAction('logout')}>{t('Potwierdz wylogowanie','Confirm sign out')}</Button></>:null}
 {surface==='auth-26'?<><p>{t('Sesja zostala zakonczona.','Your session has ended.')}</p><Button onClick={()=>onNavigate('/login')}>{t('Zaloguj sie ponownie','Sign in again')}</Button></>:null}
 {['auth-05','auth-21'].includes(surface)?<><p role="status">{busy?t('Trwa rozpoznawanie dostepu...','Resolving access...'):t('Kontynuuj zgodnie z wynikiem logowania. Przy nieudanym powrocie rozpocznij nowy proces.','Continue according to the sign-in result. If the callback failed, start a new flow.')}</p><Button disabled={!enabled} variant="secondary" onClick={()=>onNavigate('/login')}>{t('Wroc do logowania','Return to sign in')}</Button><Button disabled={!enabled||!data} onClick={()=>onNavigate('/auth/organization')}>{t('Wybierz organizacje','Choose organization')}</Button></>:null}
 {surface==='auth-27'||surface==='auth-28'?<><p>{surface==='auth-28'?t('Brak dostepu do wybranego obszaru. Popros administratora o sprawdzenie czlonkostwa.','Access is unavailable. Ask an administrator to check membership.'):t('Nie mozna teraz odczytac uslugi. Nie potwierdzono wykonania operacji.','The service cannot be reached. No operation has been confirmed.')}</p><Button disabled={busy} onClick={()=>onAction('retry')}>{t('Sprobuj ponownie','Try again')}</Button></>:null}
 {children}</section></div><footer>{t('PapaData / Konto, workspace i dane sa oddzielnymi zakresami.','PapaData / Account, workspace and data are distinct scopes.')}</footer></main>;
}
