export type HelpProcedure = {id:string;category:'data'|'access'|'analysis'|'assistant';title:readonly [string,string];summary:readonly [string,string];steps:readonly (readonly [string,string])[];route:string};
/** Product-owned guidance, not demo telemetry or a claim of provider availability. */
export const helpProcedures:readonly HelpProcedure[]=[
 {id:'data-freshness',category:'data',title:['Dane nie są aktualne','Data is not current'],summary:['Oddziel odczyt ekranu od synchronizacji źródła.','Separate a screen refresh from source synchronization.'],route:'/app/integrations',steps:[
 ['Sprawdź wybrany okres, strefę czasu i filtry.','Check the selected period, timezone and filters.'],['Otwórz Dane i integracje. Sprawdź status połączenia i historię synchronizacji.','Open Data and integrations. Check connection status and synchronization history.'],['Zanotuj kod błędu i zakres brakujących dat. Nie podawaj tokenów ani haseł w zgłoszeniu.','Record the error code and missing date range. Do not include tokens or passwords in a support request.']]},
 {id:'ga4-funnel-definitions',category:'analysis',title:['Jak czytać lejek GA4','How to read the GA4 funnel'],summary:['Liczba zdarzeń nie jest liczbą osób przechodzących kolejne kroki.','Event counts are not counts of people progressing through sequential steps.'],route:'/app/traffic?trafficView=funnel',steps:[
 ['Sprawdź definicje session_start, view_item, add_to_cart, begin_checkout i purchase w swoim pomiarze.','Check the definitions of session_start, view_item, add_to_cart, begin_checkout and purchase in your measurement setup.'],['Raport pokazuje niezależne liczniki zdarzeń. Różnica nie potwierdza odpływu osób.','The report shows independent event counts. A difference does not establish how many people dropped out.'],['Porównaj GA4 z zamówieniami przy tych samych datach. Uwzględnij różne strefy czasu, waluty i zakresy źródeł.','Compare GA4 and orders for the same dates. Account for different timezones, currencies and source populations.']]},
 {id:'customer-portfolio',category:'analysis',title:['Klienci i kohorty','Customers and cohorts'],summary:['Portfel na dzień, aktywność w okresie i pełne miesiące obserwacji.','An as-of portfolio, period activity and complete observation months.'],route:'/app/customers?customerView=cohorts',steps:[
 ['Nieaktywni klienci pozostają w portfelu. Filtry eksploratora nie zmieniają sum portfela.','Inactive customers remain in the portfolio. Explorer filters do not change portfolio totals.'],['LTV to zaobserwowany przychód, nie prognoza. Sprawdź pokrycie walut i początek historii.','LTV is observed revenue, not a forecast. Check currency coverage and the beginning of available history.'],['Kreska w kohorcie oznacza niezakończony okres, nie zerową retencję.','A dash in a cohort means an incomplete observation period, not zero retention.']]},
 {id:'access-export',category:'access',title:['Uprawnienia i eksport','Permissions and export'],summary:['Eksport może wymagać ponownego potwierdzenia tożsamości.','Export may require identity confirmation.'],route:'/app/settings',steps:[
 ['Sprawdź aktywny workspace i swoją rolę.','Check the active workspace and your role.'],['Administrator może sprawdzić dostęp zespołu. Komunikat braku uprawnień nie oznacza awarii danych.','An administrator can review team access. A permission error is not a data outage.'],['Po uwierzytelnieniu wróć do zakresu i jawnie ponów eksport. Nie wysyłaj kodów MFA do wsparcia.','After authentication, return to the range and explicitly retry the export. Do not send MFA codes to support.']]},
 {id:'assistant-evidence',category:'assistant',title:['Rozmowa, raport i decyzja','Conversation, report and decision'],summary:['Zachowaj kontekst i sprawdź dowody przed zatwierdzeniem.','Preserve context and review evidence before approval.'],route:'/app/assistant',steps:[
 ['Otwórz Papa z analizowanego ekranu i sprawdź koszyk kontekstu.','Open Papa from the analyzed screen and review the context basket.'],['Rozdziel fakt, interpretację i hipotezę. Sprawdź źródła oraz ograniczenia odpowiedzi.','Distinguish facts, interpretations and hypotheses. Review sources and response limitations.'],['Zapis decyzji nie wykonuje automatycznie zmiany u dostawcy reklamy. Ręczne odnotowanie wykonania wymaga potwierdzenia.','Saving a decision does not automatically change an advertising provider. Recording manual execution requires confirmation.']]},
];
