// Generated from contracts/auth-fsm.json — do not edit manually.
export type AuthSurfaceId = 'auth-01' | 'auth-02' | 'auth-03' | 'auth-04' | 'auth-05' | 'auth-06' | 'auth-07' | 'auth-08' | 'auth-09' | 'auth-10' | 'auth-11' | 'auth-12' | 'auth-13' | 'auth-14' | 'auth-15' | 'auth-16' | 'auth-17' | 'auth-18' | 'auth-19' | 'auth-20' | 'auth-21' | 'auth-22' | 'auth-23' | 'auth-24' | 'auth-25' | 'auth-26' | 'auth-27' | 'auth-28' | 'auth-29' | 'app-shell';
export type AuthState = 'AccessEntryReady' | 'LoginFormReady' | 'RegistrationChoiceReady' | 'EmailRegistrationReady' | 'OAuthRegistrationStarted' | 'EmailVerificationPending' | 'CompanyIdentificationReady' | 'CompanyLookupRunning' | 'CompanyDataReviewReady' | 'ManualCompanyEntryReady' | 'CompanyAlreadyRegistered' | 'RegistrationConsentsReady' | 'RegistrationProcessing' | 'RegistrationCompleted' | 'InvitationReviewReady' | 'MfaChallengeReady' | 'MfaEnrollmentReady' | 'PasswordRecoveryRequestReady' | 'PasswordRecoverySent' | 'NewPasswordReady' | 'AccessResolutionReady' | 'TenantSelectionReady' | 'WorkspaceSelectionReady' | 'ReauthenticationReady' | 'LogoutProcessing' | 'SignedOut' | 'AuthServiceUnavailable' | 'AccessBlocked' | 'EnterApplication';
export type AuthReason = 'entryRequested' | 'credentialsRequired' | 'registrationMethodRequired' | 'emailRegistrationSelected' | 'oauthRegistrationSelected' | 'emailVerificationRequired' | 'companyContextRequired' | 'companySearchRequested' | 'companyCandidateSelected' | 'companyManualEntryRequired' | 'companyAlreadyExists' | 'registrationConsentsRequired' | 'registrationSubmissionPending' | 'registrationCompleted' | 'invitationReceived' | 'mfaChallengeRequired' | 'mfaEnrollmentRequired' | 'passwordRecoveryRequested' | 'passwordRecoveryEmailSent' | 'passwordResetTokenAccepted' | 'accessContextUnresolved' | 'tenantSelectionRequired' | 'workspaceSelectionRequired' | 'freshAuthenticationRequired' | 'logoutRequested' | 'sessionTerminated' | 'authServiceUnavailable' | 'accessPolicyBlocked' | 'applicationEntryReady';
export type AuthOperationKind = 'query' | 'command' | 'callback' | 'job' | 'ui';
export interface AuthTransition { surfaceId: AuthSurfaceId; surfaceName: string; state: AuthState; reason: AuthReason; event: string; operationId: string; operationKind: AuthOperationKind; success: AuthSurfaceId[]; error: AuthSurfaceId[]; retry: AuthSurfaceId[]; guard: string; action: string; securityControl: string; }
export const authTransitions: AuthTransition[] = [
  {'surfaceId': 'auth-01', 'surfaceName': 'Wejście do Auth', 'state': 'AccessEntryReady', 'reason': 'entryRequested', 'event': 'OpenAuthEntry', 'operationId': 'access.resolve', 'operationKind': 'command', 'success': ['auth-02', 'auth-03', 'auth-15'], 'error': ['auth-27'], 'retry': ['auth-01'], 'guard': 'Resolve public entry context: invite token, expired session or normal login', 'action': 'store accessEntryReason and render selected branch', 'securityControl': 'public csrf, host allow-list, neutral error'},
  {'surfaceId': 'auth-02', 'surfaceName': 'Logowanie', 'state': 'LoginFormReady', 'reason': 'credentialsRequired', 'event': 'SubmitCredentials', 'operationId': 'auth.login', 'operationKind': 'command', 'success': ['auth-16', 'auth-29'], 'error': ['auth-28'], 'retry': [], 'guard': 'Email/password format valid and login rate budget available', 'action': 'create session challenge or active session', 'securityControl': 'csrf, credential rate limit, audit login attempt'},
  {'surfaceId': 'auth-03', 'surfaceName': 'Wejście do rejestracji', 'state': 'RegistrationChoiceReady', 'reason': 'registrationMethodRequired', 'event': 'ChooseRegistrationMethod', 'operationId': 'access.resolve', 'operationKind': 'command', 'success': ['auth-04', 'auth-05'], 'error': ['auth-27'], 'retry': ['auth-03'], 'guard': 'Registration feature enabled for tenant policy', 'action': 'persist registration method choice', 'securityControl': 'csrf, anti-enumeration, invite context preserved'},
  {'surfaceId': 'auth-04', 'surfaceName': 'Rejestracja adresem e-mail', 'state': 'EmailRegistrationReady', 'reason': 'emailRegistrationSelected', 'event': 'SubmitEmailRegistration', 'operationId': 'auth.register.email', 'operationKind': 'command', 'success': ['auth-12'], 'error': ['auth-28'], 'retry': [], 'guard': 'Email, password and invite constraints valid', 'action': 'create pending registration draft', 'securityControl': 'csrf, password policy, anti-enumeration, audit'},
  {'surfaceId': 'auth-05', 'surfaceName': 'Rejestracja przez OAuth', 'state': 'OAuthRegistrationStarted', 'reason': 'oauthRegistrationSelected', 'event': 'StartOAuth', 'operationId': 'auth.oauth.start', 'operationKind': 'command', 'success': ['auth-06', 'auth-13'], 'error': ['auth-27'], 'retry': ['auth-05'], 'guard': 'OAuth provider selected and redirect URI allowed', 'action': 'create OAuth state and wait for signed provider callback', 'securityControl': 'state nonce, PKCE, provider allow-list'},
  {'surfaceId': 'auth-06', 'surfaceName': 'Weryfikacja adresu e-mail', 'state': 'EmailVerificationPending', 'reason': 'emailVerificationRequired', 'event': 'VerifyEmailToken', 'operationId': 'auth.email.verify', 'operationKind': 'command', 'success': ['auth-13'], 'error': ['auth-06', 'auth-27'], 'retry': [], 'guard': 'Token exists, not expired, matches pending user', 'action': 'mark email verified and continue registration', 'securityControl': 'single-use token, replay protection, neutral invalid token copy'},
  {'surfaceId': 'auth-07', 'surfaceName': 'Identyfikacja firmy', 'state': 'CompanyIdentificationReady', 'reason': 'companyContextRequired', 'event': 'SubmitCompanyIdentity', 'operationId': 'company.lookup', 'operationKind': 'query', 'success': ['auth-08', 'auth-10', 'auth-11'], 'error': ['auth-27'], 'retry': ['auth-07'], 'guard': 'NIP/domain provided and lookup provider available', 'action': 'resolve candidate company or manual path', 'securityControl': 'rate limit registry lookup, no company enumeration'},
  {'surfaceId': 'auth-08', 'surfaceName': 'Wyszukiwanie firmy', 'state': 'CompanyLookupRunning', 'reason': 'companySearchRequested', 'event': 'SelectCompanyCandidate', 'operationId': 'company.lookup', 'operationKind': 'query', 'success': ['auth-09'], 'error': ['auth-10'], 'retry': [], 'guard': 'Registry returned candidate company data', 'action': 'attach registry candidate to onboarding draft', 'securityControl': 'provider timeout budget, provenance logged'},
  {'surfaceId': 'auth-09', 'surfaceName': 'Sprawdzenie i edycja danych firmy', 'state': 'CompanyDataReviewReady', 'reason': 'companyCandidateSelected', 'event': 'ConfirmCompanyData', 'operationId': 'company.draft.update', 'operationKind': 'command', 'success': ['auth-12'], 'error': ['auth-10'], 'retry': [], 'guard': 'User can confirm or correct registry data', 'action': 'persist company draft fields and provenance', 'securityControl': 'input validation, audit company draft change'},
  {'surfaceId': 'auth-10', 'surfaceName': 'Ręczne wprowadzenie firmy', 'state': 'ManualCompanyEntryReady', 'reason': 'companyManualEntryRequired', 'event': 'SubmitManualCompany', 'operationId': 'company.draft.update', 'operationKind': 'command', 'success': ['auth-12'], 'error': ['auth-10'], 'retry': [], 'guard': 'Required legal fields supplied manually', 'action': 'persist manual company draft', 'securityControl': 'validation, no external provider dependency'},
  {'surfaceId': 'auth-11', 'surfaceName': 'Firma już zarejestrowana', 'state': 'CompanyAlreadyRegistered', 'reason': 'companyAlreadyExists', 'event': 'ResolveExistingCompany', 'operationId': 'invitation.request', 'operationKind': 'command', 'success': ['auth-15', 'auth-28'], 'error': ['auth-27'], 'retry': ['auth-11'], 'guard': 'Company match exists and user has no membership', 'action': 'offer invite/access request path without leaking tenant data', 'securityControl': 'tenant privacy, neutral copy, support audit'},
  {'surfaceId': 'auth-12', 'surfaceName': 'Zgody rejestracyjne', 'state': 'RegistrationConsentsReady', 'reason': 'registrationConsentsRequired', 'event': 'AcceptConsents', 'operationId': 'auth.consents.accept', 'operationKind': 'command', 'success': ['auth-13'], 'error': ['auth-12'], 'retry': [], 'guard': 'Required consents selected with version ids', 'action': 'store consent receipts and continue finalize', 'securityControl': 'consent versioning, audit, no prechecked optional consents'},
  {'surfaceId': 'auth-13', 'surfaceName': 'Przetwarzanie rejestracji', 'state': 'RegistrationProcessing', 'reason': 'registrationSubmissionPending', 'event': 'FinalizeRegistration', 'operationId': 'auth.registration.finalize', 'operationKind': 'job', 'success': ['auth-14'], 'error': ['auth-27'], 'retry': ['auth-13'], 'guard': 'Email/company/consent preconditions complete', 'action': 'create user, tenant/workspace bootstrap job or membership binding', 'securityControl': 'transactional audit, idempotency key'},
  {'surfaceId': 'auth-14', 'surfaceName': 'Rejestracja zakończona', 'state': 'RegistrationCompleted', 'reason': 'registrationCompleted', 'event': 'ContinueAfterRegistration', 'operationId': 'access.bootstrap', 'operationKind': 'command', 'success': ['auth-21', 'auth-29'], 'error': ['auth-27'], 'retry': [], 'guard': 'Registration finalize job completed', 'action': 'bootstrap first access context', 'securityControl': 'session rotation, onboarding marker'},
  {'surfaceId': 'auth-15', 'surfaceName': 'Przegląd zaproszenia', 'state': 'InvitationReviewReady', 'reason': 'invitationReceived', 'event': 'AcceptInvitation', 'operationId': 'invitation.validate', 'operationKind': 'command', 'success': ['auth-02', 'auth-04', 'auth-21'], 'error': ['auth-28'], 'retry': [], 'guard': 'Invitation token valid and recipient matches', 'action': 'bind invite context to auth journey', 'securityControl': 'single-use invite token, recipient verification'},
  {'surfaceId': 'auth-16', 'surfaceName': 'Weryfikacja MFA', 'state': 'MfaChallengeReady', 'reason': 'mfaChallengeRequired', 'event': 'VerifyMfaCode', 'operationId': 'auth.mfa.verify', 'operationKind': 'command', 'success': ['auth-21', 'auth-29'], 'error': ['auth-16', 'auth-28'], 'retry': [], 'guard': 'Challenge id active and attempts remain', 'action': 'complete step-up or login session', 'securityControl': 'attempt limit, TOTP/WebAuthn validation, audit'},
  {'surfaceId': 'auth-17', 'surfaceName': 'Konfiguracja MFA', 'state': 'MfaEnrollmentReady', 'reason': 'mfaEnrollmentRequired', 'event': 'EnrollMfaFactor', 'operationId': 'auth.mfa.enroll', 'operationKind': 'command', 'success': ['auth-16'], 'error': ['auth-17'], 'retry': [], 'guard': 'Privileged or policy-required MFA enrollment active', 'action': 'create MFA secret/challenge and require confirmation through auth-16', 'securityControl': 'secret masking, recovery codes once, audit'},
  {'surfaceId': 'auth-18', 'surfaceName': 'Prośba o odzyskanie hasła', 'state': 'PasswordRecoveryRequestReady', 'reason': 'passwordRecoveryRequested', 'event': 'RequestPasswordRecovery', 'operationId': 'auth.password.recovery.request', 'operationKind': 'command', 'success': ['auth-19'], 'error': ['auth-18'], 'retry': [], 'guard': 'Email syntactically valid and rate budget available', 'action': 'send neutral recovery message if account eligible', 'securityControl': 'anti-enumeration, rate limit, mail audit'},
  {'surfaceId': 'auth-19', 'surfaceName': 'Informacja o wysłaniu resetu', 'state': 'PasswordRecoverySent', 'reason': 'passwordRecoveryEmailSent', 'event': 'OpenResetLink', 'operationId': 'auth.password.recovery.token.validate', 'operationKind': 'callback', 'success': ['auth-20'], 'error': ['auth-18'], 'retry': ['auth-19'], 'guard': 'Reset token arrives from email deep link and is valid', 'action': 'unlock password reset surface for token owner', 'securityControl': 'single-use token, expiry, neutral invalid copy'},
  {'surfaceId': 'auth-20', 'surfaceName': 'Ustawienie nowego hasła', 'state': 'NewPasswordReady', 'reason': 'passwordResetTokenAccepted', 'event': 'SubmitNewPassword', 'operationId': 'auth.password.reset', 'operationKind': 'command', 'success': ['auth-02'], 'error': ['auth-20', 'auth-28'], 'retry': [], 'guard': 'Token valid and password policy satisfied', 'action': 'rotate credentials and revoke active sessions', 'securityControl': 'password policy, session revoke, audit'},
  {'surfaceId': 'auth-21', 'surfaceName': 'Rozwiązanie dostępu', 'state': 'AccessResolutionReady', 'reason': 'accessContextUnresolved', 'event': 'ResolveAccessContext', 'operationId': 'access.resolve', 'operationKind': 'command', 'success': ['auth-22', 'auth-23', 'auth-29'], 'error': ['auth-28'], 'retry': [], 'guard': 'Authenticated session exists and memberships are loaded', 'action': 'resolve tenant/workspace target', 'securityControl': 'tenant isolation, membership filter'},
  {'surfaceId': 'auth-22', 'surfaceName': 'Wybór organizacji lub tenanta', 'state': 'TenantSelectionReady', 'reason': 'tenantSelectionRequired', 'event': 'SelectTenant', 'operationId': 'access.tenant.select', 'operationKind': 'command', 'success': ['auth-23', 'auth-29'], 'error': ['auth-28'], 'retry': [], 'guard': 'User has more than one tenant membership', 'action': 'store selected tenant context', 'securityControl': 'membership check, no cross-tenant leakage'},
  {'surfaceId': 'auth-23', 'surfaceName': 'Wybór obszaru roboczego', 'state': 'WorkspaceSelectionReady', 'reason': 'workspaceSelectionRequired', 'event': 'SelectWorkspace', 'operationId': 'access.workspace.select', 'operationKind': 'command', 'success': ['auth-29'], 'error': ['auth-28'], 'retry': [], 'guard': 'Selected workspace belongs to selected tenant and user membership', 'action': 'activate workspace context', 'securityControl': 'workspace membership, data-scope audit'},
  {'surfaceId': 'auth-24', 'surfaceName': 'Ponowne uwierzytelnienie', 'state': 'ReauthenticationReady', 'reason': 'freshAuthenticationRequired', 'event': 'SubmitReauthentication', 'operationId': 'auth.reauthenticate', 'operationKind': 'command', 'success': ['auth-29'], 'error': ['auth-28'], 'retry': [], 'guard': 'Sensitive operation requires fresh auth', 'action': 'issue step-up proof for original operation', 'securityControl': 'step-up TTL, audit, original operation binding'},
  {'surfaceId': 'auth-25', 'surfaceName': 'Przetwarzanie wylogowania', 'state': 'LogoutProcessing', 'reason': 'logoutRequested', 'event': 'StartLogout', 'operationId': 'auth.logout', 'operationKind': 'command', 'success': ['auth-26'], 'error': ['auth-27'], 'retry': ['auth-25'], 'guard': 'Active session or logout request exists', 'action': 'revoke session and clear cookies', 'securityControl': 'csrf, session revoke, cookie clearing'},
  {'surfaceId': 'auth-26', 'surfaceName': 'Ekran po wylogowaniu', 'state': 'SignedOut', 'reason': 'sessionTerminated', 'event': 'ReturnToLogin', 'operationId': 'ui.return_to_login', 'operationKind': 'ui', 'success': ['auth-02'], 'error': ['auth-27'], 'retry': [], 'guard': 'No active authenticated session remains', 'action': 'navigate to login without BFF mutation', 'securityControl': 'no sensitive data retained in browser state'},
  {'surfaceId': 'auth-27', 'surfaceName': 'Usługa Auth niedostępna', 'state': 'AuthServiceUnavailable', 'reason': 'authServiceUnavailable', 'event': 'RetryAuthService', 'operationId': 'auth.status.read', 'operationKind': 'query', 'success': ['auth-01'], 'error': ['auth-27'], 'retry': ['auth-27'], 'guard': 'Service health can be checked without exposing user data', 'action': 'retry status check or show support contact', 'securityControl': 'neutral error, no secret in diagnostics'},
  {'surfaceId': 'auth-28', 'surfaceName': 'Dostęp zablokowany', 'state': 'AccessBlocked', 'reason': 'accessPolicyBlocked', 'event': 'RequestSupportOrRetry', 'operationId': 'auth.access.blocked.read', 'operationKind': 'query', 'success': ['auth-18', 'auth-27'], 'error': ['auth-28'], 'retry': ['auth-28'], 'guard': 'Block reason available for current session or invite context', 'action': 'show safe recovery path', 'securityControl': 'no tenant data leakage, support audit'},
  {'surfaceId': 'auth-29', 'surfaceName': 'Zakończenie procesu i wejście do aplikacji', 'state': 'EnterApplication', 'reason': 'applicationEntryReady', 'event': 'EnterApplication', 'operationId': 'access.bootstrap', 'operationKind': 'command', 'success': ['app-shell'], 'error': ['auth-27'], 'retry': [], 'guard': 'Tenant/workspace resolved and session active', 'action': 'enter app shell with active workspace', 'securityControl': 'session rotation, workspace scope lock'},
];
