import type {Meta,StoryObj} from '@storybook/react-vite';
import {AccessScenario} from '../../../fixtures/access/AccessScenario';
const meta={title:'25 Dostep / ZIP 4 / Katalog 29 powierzchni',parameters:{layout:'fullscreen'}} satisfies Meta;
export default meta;
type Story=StoryObj<typeof meta>;
export const Auth01:Story={name:'auth-01',render:()=> <AccessScenario surface="auth-01"/>};
export const Auth02:Story={name:'auth-02',render:()=> <AccessScenario surface="auth-02"/>};
export const Auth03:Story={name:'auth-03',render:()=> <AccessScenario surface="auth-03"/>};
export const Auth04:Story={name:'auth-04',render:()=> <AccessScenario surface="auth-04"/>};
export const Auth05:Story={name:'auth-05',render:()=> <AccessScenario surface="auth-05"/>};
export const Auth06:Story={name:'auth-06',render:()=> <AccessScenario surface="auth-06"/>};
export const Auth07:Story={name:'auth-07',render:()=> <AccessScenario surface="auth-07"/>};
export const Auth08:Story={name:'auth-08',render:()=> <AccessScenario surface="auth-08"/>};
export const Auth09:Story={name:'auth-09',render:()=> <AccessScenario surface="auth-09"/>};
export const Auth10:Story={name:'auth-10',render:()=> <AccessScenario surface="auth-10"/>};
export const Auth11:Story={name:'auth-11',render:()=> <AccessScenario surface="auth-11"/>};
export const Auth12:Story={name:'auth-12',render:()=> <AccessScenario surface="auth-12"/>};
export const Auth13:Story={name:'auth-13',render:()=> <AccessScenario surface="auth-13"/>};
export const Auth14:Story={name:'auth-14',render:()=> <AccessScenario surface="auth-14"/>};
export const Auth15:Story={name:'auth-15',render:()=> <AccessScenario surface="auth-15"/>};
export const Auth16:Story={name:'auth-16',render:()=> <AccessScenario surface="auth-16"/>};
export const Auth17:Story={name:'auth-17',render:()=> <AccessScenario surface="auth-17"/>};
export const Auth18:Story={name:'auth-18',render:()=> <AccessScenario surface="auth-18"/>};
export const Auth19:Story={name:'auth-19',render:()=> <AccessScenario surface="auth-19"/>};
export const Auth20:Story={name:'auth-20',render:()=> <AccessScenario surface="auth-20"/>};
export const Auth21:Story={name:'auth-21',render:()=> <AccessScenario surface="auth-21"/>};
export const Auth22:Story={name:'auth-22',render:()=> <AccessScenario surface="auth-22"/>};
export const Auth23:Story={name:'auth-23',render:()=> <AccessScenario surface="auth-23"/>};
export const Auth24:Story={name:'auth-24',render:()=> <AccessScenario surface="auth-24"/>};
export const Auth25:Story={name:'auth-25',render:()=> <AccessScenario surface="auth-25"/>};
export const Auth26:Story={name:'auth-26',render:()=> <AccessScenario surface="auth-26"/>};
export const Auth27:Story={name:'auth-27',render:()=> <AccessScenario surface="auth-27"/>};
export const Auth28:Story={name:'auth-28',render:()=> <AccessScenario surface="auth-28"/>};
export const Auth29:Story={name:'auth-29',render:()=> <AccessScenario surface="auth-29"/>};
export const Failed:Story={name:'Blad bez utraty danych',render:()=> <AccessScenario surface="auth-07" failed/>};
