import { businessChange, type BusinessMetricId, type BusinessOverview } from '@papadata/contracts';
import { Button } from '../../design-system';
import type { RemoteState } from '../../runtime/shared/data/useRemoteResource';
import { useProductQuery, contextualProductLink, productRoutes } from '../../runtime/app/routing/productRoutes';
import { useShellNavigate } from '../../runtime/shell/app-shell/ShellNavigationContext';
import { useAssistantAnalysisContext } from '../../runtime/shell/papa-assistant/useAssistantAnalysisContext';
import { DataProvenance, MetricSummary, ProductDataState } from '../shared/ProductDataState';
import { useProductLocale } from '../shared/useProductLocale';
import { CommerceScope, commerceSourcePath } from '../commerce/CommerceScope';
import { CommerceTrend } from '../commerce/CommerceTrend';
import { commerceMoney, commerceNumber, commerceState } from '../commerce/commercePresentation';
export const businessLabels:Record<BusinessMetricId,readonly [string,string]>={gross:['Brutto kwalifikowane','Qualified gross'],orders:['Zamówienia kwalifikowane','Qualified orders'],refunds:['Refundacje w okresie','Refund flow'],afterRefunds:['Brutto minus refundacje','Gross less refund flow'],adSpend:['Koszt reklam workspace','Workspace advertising cost'],margin:['Marża biznesowa','Business margin']};
export type BusinessOverviewProps={readonly data:BusinessOverview|null;readonly state:RemoteState;readonly problem?:string|null;readonly onReload?:()=>void};
export function BusinessOverviewScreen({data,state,problem,onReload}:BusinessOverviewProps) {
  const {t,language}=useProductLocale(),{params,update}=useProductQuery(),navigate=useShellNavigate();
  const metric:BusinessMetricId=Object.keys(businessLabels).includes(params.get('overviewMetric')??'')?params.get('overviewMetric') as BusinessMetricId:'gross';
  const format=(value:number|null|undefined,id:BusinessMetricId)=>id==='orders'?commerceNumber(value,language):commerceMoney(value,data?.meta.currency,language);
  const link=(target:string,extras:Record<string,string|null>={})=>contextualProductLink(target,{sourceId:data?.meta.sourceId??null,currency:data?.meta.currency??null,returnTo:commerceSourcePath(data?.meta??null),...extras});
  useAssistantAnalysisContext({title:'Centrum Dowodzenia',route:productRoutes.overview,readiness:state==='ready'?data?.meta.quality??'empty':state,source:'business.overview.v1',
    metrics:Object.fromEntries(data?.metrics.map(row=>[businessLabels[row.id][0],row.value])??[]),tables:['Wynik bieżący i poprzedni'],charts:['Trend wyniku']});
  return <div className="pd-product-data pd-commerce"><CommerceScope title={t('Centrum Dowodzenia','Command Center')} description={t('Wynik sprzedaży, jego pochodzenie i otwarte decyzje. Brak danych pozostaje widoczny.','Sales performance, its provenance and open decisions. Missing data stays visible.')} meta={data?.meta??null} onReload={onReload} template="overview"/>
    <div className="pd-product-data__toolbar"><label>{t('Porównanie','Compare')}<select disabled={!data?.comparisonAllowed} value={params.get('compare')==='year'?'year':'previous'} onChange={event=>update({compare:event.target.value})}><option value="previous">{t('Poprzedni okres tej samej długości','Previous equal-length period')}</option><option value="year">{t('Rok wcześniej, tyle samo dni','Year earlier, same number of days')}</option></select></label>
    {data&&!data.comparisonAllowed&&<p role="status">{t('Brak uprawnienia do porównania okresów.','No permission to compare periods.')}</p>}{data&&<p className="pd-commerce__muted">{data.meta.range.from} – {data.meta.range.to} / {data.comparison.from} – {data.comparison.to} · {data.meta.range.timezone}</p>}</div>
    <ProductDataState state={commerceState(data?.meta,state)} problem={problem??(data?.meta.quality==='selection_required'?t('Wybierz jedno zrodlo w filtrze powyzej. Nie laczymy nakladajacych sie kont.','Choose one source above. Overlapping accounts are not combined.'):undefined)} onRetry={onReload}>{data&&<>
      <DataProvenance source={data.meta.sources.find(s=>s.id===data.meta.sourceId)?.name??t('Wybór źródła','Source selection')} synchronizedAt={data.meta.lastSuccessfulSyncAt} calculatedAt={data.meta.generatedAt} limitations={data.meta.limitations} demo={data.meta.mode==='demo'}/>
      <dl className="pd-product-data__metrics">{data.metrics.map(item=>{const change=businessChange(item.value,item.previous);return <MetricSummary key={item.id} label={t(...businessLabels[item.id])} value={format(item.value,item.id)} description={t(`Poprzednio: ${format(item.previous,item.id)}. Zmiana: ${change===null?'nieporównywalna':commerceNumber(change,language)+'%'}.`,`Previously: ${format(item.previous,item.id)}. Change: ${change===null?'not comparable':commerceNumber(change,language)+'%'}.`)}/>;})}</dl>
      <div className="pd-commerce__analysis"><div><div className="pd-product-data__toolbar"><label>{t('Miara trendu','Trend metric')}<select value={metric} onChange={event=>update({overviewMetric:event.target.value})}>{Object.entries(businessLabels).map(([id,label])=><option key={id} value={id}>{t(...label)}</option>)}</select></label></div>
        <CommerceTrend title={t(...businessLabels[metric])} points={data.points.map(row=>({date:row.date,value:row.values[metric],previous:row.previous[metric],previousDate:row.previousDate}))} unit={metric==='orders'?t('szt.','units'):data.meta.currency??t('Waluta nieustalona','Currency unavailable')}/>
        <p className="pd-commerce__muted">{t('Poprzedni szereg jest wyrównany do kolejnego dnia porównywanego okresu. Daty obu zakresów są podane nad wykresem.','The previous series is aligned by day index. Both exact periods are displayed above the chart.')}</p></div>
        <aside className="pd-commerce__side"><h2>{t('Otwarte decyzje','Open decisions')}</h2><p className="pd-commerce__muted">{t('Bieżący rejestr workspace, niezależny od zakresu dat analizy.','Current workspace register, independent of the analysis period.')}</p>
          {data.decisions.status==='ready'?data.decisions.records.length?<ul>{data.decisions.records.map(item=><li key={item.id}><Button variant="ghost" size="small" onClick={()=>navigate(link(productRoutes.decisions,{decisionId:item.id}))}>{item.title}</Button><small>{item.owner??t('Brak właściciela','No owner')} · {item.due??t('Bez terminu','No due date')} · {item.status}</small></li>)}</ul>:<p>{t('Rejestr nie zawiera otwartych pozycji. Nie jest to potwierdzenie braku ryzyka.','The register contains no open items. This is not proof that no risks exist.')}</p>:<p role="status">{data.decisions.status==='forbidden'?t('Brak uprawnień do rejestru decyzji.','No permission to read decisions.'):t('Nie udało się pobrać decyzji. Wynik nie został zastąpiony zerem.','Decisions could not be read. The result has not been replaced with zero.')}</p>}
          {data.decisions.status==='ready'&&<Button variant="secondary" size="small" onClick={()=>navigate(link(productRoutes.decisions))}>{t(`Cały rejestr (${data.decisions.total??0})`,`Full register (${data.decisions.total??0})`)}</Button>}
        </aside>
      </div>
      <section className="pd-product-data__section"><h2>{t('Definicje, braki i działania','Definitions, missing data and actions')}</h2>
        {data.metrics.map(item=><details className="pd-commerce__definition" key={item.id}><summary>{t(...businessLabels[item.id])} · {format(item.value,item.id)}</summary><p>{item.definition}</p>{item.limitation&&<p>{item.limitation}</p>}<p>{t('Potwierdzony czas synchronizacji','Source synchronization')}: {item.synchronizedAt??t('Nieudostępniony','Unavailable')}</p></details>)}
        {data.advertising.limitation&&<p role="status">{data.advertising.limitation}</p>}
        <div className="pd-product-data__toolbar"><Button variant="secondary" onClick={()=>navigate(link(productRoutes.orders))}>{t('Zamówienia źródłowe','Source orders')}</Button><Button variant="secondary" onClick={()=>navigate(link(productRoutes.products))}>{t('Wyniki produktów','Product performance')}</Button><Button variant="ghost" onClick={()=>navigate(link(productRoutes.campaigns,{sourceId:null}))}>{t('Perspektywa reklam','Advertising perspective')}</Button><Button variant="ghost" onClick={()=>navigate(link(productRoutes.integrations))}>{t('Stan źródeł','Source health')}</Button></div>
      </section>
    </>}</ProductDataState>
  </div>;
}
